# Generated by Django 2.0.6 on 2018-06-27 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.CharField(max_length=100)),
                ('date', models.DateTimeField(verbose_name='date of data')),
                ('rain', models.FloatField(default=None)),
            ],
        ),
    ]
