# Generated by Django 2.0.6 on 2018-06-28 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='INS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NUM_POSTE', models.IntegerField()),
                ('DATJ', models.DateTimeField(verbose_name='date of data')),
                ('DATRECU', models.DateTimeField(verbose_name='Date de réception des données')),
                ('RR5MN', models.FloatField(verbose_name='Hauteur des précipitations sur 5min')),
                ('RRI', models.FloatField(verbose_name='Intensité instantanée max des précipitations')),
                ('FF', models.FloatField(verbose_name='Force du vent moyenné sur 10min (m/s)')),
                ('DD', models.IntegerField(verbose_name='Direction du vent moyenné sur 10min (°)')),
                ('FXI3S', models.FloatField(verbose_name='Rafales 2.5s max (m/s)')),
            ],
        ),
        migrations.DeleteModel(
            name='Archive',
        ),
    ]
