# Generated by Django 2.0.6 on 2018-06-28 12:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_auto_20180628_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ins',
            name='DATJ',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date of data'),
        ),
        migrations.AlterField(
            model_name='ins',
            name='DATRECU',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de réception des données'),
        ),
    ]
