# Generated by Django 2.0.6 on 2018-07-03 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_auto_20180628_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='PAYS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CODPAYS', models.IntegerField()),
                ('NOMPAYS', models.TextField()),
            ],
            options={
                'verbose_name': 'Liste des pays',
            },
        ),
        migrations.DeleteModel(
            name='INS',
        ),
    ]
