# Generated by Django 2.0.6 on 2018-07-03 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_auto_20180703_1011'),
    ]

    operations = [
        migrations.CreateModel(
            name='COMMUNE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('COMMUNE', models.TextField()),
                ('CODPAYS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.PAYS')),
            ],
        ),
    ]
