# Generated by Django 2.0.6 on 2018-07-03 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_ins'),
    ]

    operations = [
        migrations.DeleteModel(
            name='INS',
        ),
    ]
