# Generated by Django 2.0.6 on 2018-07-05 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0009_auto_20180704_1548'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commune',
            options={'verbose_name': 'Commune'},
        ),
        migrations.AlterField(
            model_name='commune',
            name='CODPAYS',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='gestion.PAYS'),
        ),
        migrations.AlterField(
            model_name='commune',
            name='COMMUNE',
            field=models.CharField(default=None, max_length=25),
        ),
        migrations.AlterField(
            model_name='pays',
            name='CODPAYS',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='pays',
            name='NOMPAYS',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='poste',
            name='ADRESSE',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='poste',
            name='ALT',
            field=models.FloatField(default=None, verbose_name='Altitude du poste en m'),
        ),
        migrations.AlterField(
            model_name='poste',
            name='AUT',
            field=models.IntegerField(default=None, verbose_name='Autorisation de stockage/diffusion'),
        ),
        migrations.AlterField(
            model_name='poste',
            name='CODE_POSTE',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='poste',
            name='COMM',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='poste',
            name='CP',
            field=models.IntegerField(default=None, verbose_name='Code postal'),
        ),
        migrations.AlterField(
            model_name='poste',
            name='DATEFERM',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='poste',
            name='DATEOUV',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='poste',
            name='LAT',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='poste',
            name='LIEU_DIT',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='poste',
            name='LON',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='poste',
            name='MAINT',
            field=models.IntegerField(default=None, verbose_name='Code maintenance (tableau)'),
        ),
        migrations.AlterField(
            model_name='poste',
            name='MEL',
            field=models.CharField(default=None, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='poste',
            name='NOM',
            field=models.CharField(default=None, max_length=10, verbose_name='Nom du poste (ex : NDLP)'),
        ),
        migrations.AlterField(
            model_name='poste',
            name='POS',
            field=models.IntegerField(default=None, verbose_name='Personne physique(1) - Morale (2)'),
        ),
        migrations.AlterField(
            model_name='poste',
            name='PROP',
            field=models.CharField(default=None, max_length=20, verbose_name='Nom du propriétaire/entreprise'),
        ),
        migrations.AlterField(
            model_name='poste',
            name='REF_MF',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='poste',
            name='TEL',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='poste',
            name='TYPE',
            field=models.CharField(default=None, max_length=20, verbose_name='Modèle de station'),
        ),
        migrations.AlterField(
            model_name='poste',
            name='TYPINFO',
            field=models.CharField(default=None, max_length=20, verbose_name='Type de donnees (route,agricole,pédagogique,..)'),
        ),
        migrations.AlterField(
            model_name='poste',
            name='VILLE',
            field=models.CharField(default=None, max_length=25),
        ),
    ]
