# Generated by Django 2.0.6 on 2018-07-05 05:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0010_auto_20180705_0923'),
    ]

    operations = [
        migrations.CreateModel(
            name='INST',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DATJ', models.DateTimeField(default=django.utils.timezone.now, verbose_name='AAAA-MM-JJ HH-MM de la mesure')),
                ('DATRECU', models.DateTimeField(default=django.utils.timezone.now, verbose_name='AAAA-MM-JJ HH-MM de la derniere modification')),
                ('RR', models.FloatField(default=None, null=True)),
                ('RRI', models.FloatField(default=None, null=True, verbose_name='Intensité max des precipitations')),
                ('FF', models.FloatField(default=None, null=True)),
                ('DD', models.FloatField(default=None, null=True)),
                ('FXI', models.FloatField(default=None, null=True)),
                ('DXI', models.FloatField(default=None, null=True)),
                ('T', models.FloatField(default=None, null=True)),
                ('TD', models.FloatField(default=None, null=True)),
                ('U', models.FloatField(default=None, null=True)),
                ('PMER', models.FloatField(default=None, null=True)),
                ('UV', models.FloatField(default=None, null=True, verbose_name='Indice UV')),
                ('RAD', models.FloatField(default=None, null=True)),
                ('IC', models.FloatField(default=None, null=True, verbose_name='Indice de chaleur')),
                ('WINDCHILL', models.FloatField(default=None, null=True)),
                ('ETP', models.FloatField(default=None, null=True, verbose_name='Evapotranspiration')),
                ('HF', models.FloatField(default=None, null=True, verbose_name='Humidite du feuillage')),
                ('HS', models.FloatField(default=None, null=True, verbose_name='Humidite du sol')),
                ('TS', models.FloatField(default=None, null=True, verbose_name='Temperature du sol')),
                ('NUM_POSTE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.POSTE')),
            ],
        ),
        migrations.DeleteModel(
            name='INS',
        ),
    ]
