# Generated by Django 2.0.6 on 2018-07-05 07:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0011_auto_20180705_0927'),
    ]

    operations = [
        migrations.CreateModel(
            name='INSTAN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DATJ', models.DateTimeField(default=django.utils.timezone.now, verbose_name='AAAA-MM-JJ HH-MM de la mesure')),
                ('DATRECU', models.DateTimeField(default=django.utils.timezone.now, verbose_name='AAAA-MM-JJ HH-MM de la derniere modification')),
                ('RR', models.FloatField(default=None, null=True)),
                ('RRI', models.FloatField(default=None, null=True, verbose_name='Intensité max des precipitations')),
                ('FF', models.FloatField(default=None, null=True)),
                ('DD', models.FloatField(default=None, null=True)),
                ('FXI', models.FloatField(default=None, null=True)),
                ('DXI', models.FloatField(default=None, null=True)),
                ('T', models.FloatField(default=None, null=True)),
                ('TD', models.FloatField(default=None, null=True)),
                ('U', models.FloatField(default=None, null=True)),
                ('PMER', models.FloatField(default=None, null=True)),
                ('UV', models.FloatField(default=None, null=True, verbose_name='Indice UV')),
                ('RAD', models.FloatField(default=None, null=True)),
                ('IC', models.FloatField(default=None, null=True, verbose_name='Indice de chaleur')),
                ('WINDCHILL', models.FloatField(default=None, null=True)),
                ('ETP', models.FloatField(default=None, null=True, verbose_name='Evapotranspiration')),
                ('HF', models.FloatField(default=None, null=True, verbose_name='Humidite du feuillage')),
                ('HS', models.FloatField(default=None, null=True, verbose_name='Humidite du sol')),
                ('TS', models.FloatField(default=None, null=True, verbose_name='Temperature du sol')),
            ],
        ),
        migrations.RemoveField(
            model_name='inst',
            name='NUM_POSTE',
        ),
        migrations.AlterModelOptions(
            name='pays',
            options={'verbose_name': 'Pays'},
        ),
        migrations.RenameField(
            model_name='decadq',
            old_name='NUM_POSTE',
            new_name='POSTE',
        ),
        migrations.RenameField(
            model_name='h',
            old_name='NUM_POSTE',
            new_name='POSTE',
        ),
        migrations.RenameField(
            model_name='histmaint',
            old_name='NUM_POSTE',
            new_name='POSTE',
        ),
        migrations.RenameField(
            model_name='histpost',
            old_name='NUM_POSTE',
            new_name='POSTE',
        ),
        migrations.RenameField(
            model_name='instrument',
            old_name='NUM_POSTE',
            new_name='POSTE',
        ),
        migrations.RenameField(
            model_name='maintenance',
            old_name='NUM_POSTE',
            new_name='POSTE',
        ),
        migrations.RenameField(
            model_name='mensq',
            old_name='NUM_POSTE',
            new_name='POSTE',
        ),
        migrations.RenameField(
            model_name='panne',
            old_name='NUM_POSTE',
            new_name='POSTE',
        ),
        migrations.RenameField(
            model_name='q',
            old_name='NUM_POSTE',
            new_name='POSTE',
        ),
        migrations.RenameField(
            model_name='recmens',
            old_name='NUM_POSTE',
            new_name='POSTE',
        ),
        migrations.RemoveField(
            model_name='poste',
            name='ADRESSE',
        ),
        migrations.RemoveField(
            model_name='poste',
            name='ALT',
        ),
        migrations.RemoveField(
            model_name='poste',
            name='AUT',
        ),
        migrations.RemoveField(
            model_name='poste',
            name='CODE_POSTE',
        ),
        migrations.RemoveField(
            model_name='poste',
            name='COMM',
        ),
        migrations.RemoveField(
            model_name='poste',
            name='COMMUNE',
        ),
        migrations.RemoveField(
            model_name='poste',
            name='CP',
        ),
        migrations.RemoveField(
            model_name='poste',
            name='DATEFERM',
        ),
        migrations.RemoveField(
            model_name='poste',
            name='DATEOUV',
        ),
        migrations.RemoveField(
            model_name='poste',
            name='LAT',
        ),
        migrations.RemoveField(
            model_name='poste',
            name='LIEU_DIT',
        ),
        migrations.RemoveField(
            model_name='poste',
            name='LON',
        ),
        migrations.RemoveField(
            model_name='poste',
            name='MAINT',
        ),
        migrations.RemoveField(
            model_name='poste',
            name='MEL',
        ),
        migrations.RemoveField(
            model_name='poste',
            name='POS',
        ),
        migrations.RemoveField(
            model_name='poste',
            name='PROP',
        ),
        migrations.RemoveField(
            model_name='poste',
            name='REF_MF',
        ),
        migrations.RemoveField(
            model_name='poste',
            name='TEL',
        ),
        migrations.RemoveField(
            model_name='poste',
            name='TYPE',
        ),
        migrations.RemoveField(
            model_name='poste',
            name='TYPINFO',
        ),
        migrations.RemoveField(
            model_name='poste',
            name='VILLE',
        ),
        migrations.AlterField(
            model_name='poste',
            name='NOM',
            field=models.CharField(default=None, max_length=20, verbose_name='Nom du poste (ex : NDLP)'),
        ),
        migrations.DeleteModel(
            name='INST',
        ),
        migrations.AddField(
            model_name='instan',
            name='POSTE',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.POSTE'),
        ),
    ]
