# Generated by Django 2.0.6 on 2018-07-05 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0012_auto_20180705_1109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commune',
            old_name='COMMUNE',
            new_name='NOMCOMMUNE',
        ),
        migrations.RenameField(
            model_name='commune',
            old_name='CODPAYS',
            new_name='PAYS',
        ),
    ]
