# Generated by Django 2.0.6 on 2018-07-06 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0013_auto_20180705_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='poste',
            name='ADRESSE',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='poste',
            name='ALT',
            field=models.FloatField(default=None, verbose_name='Altitude du poste en m'),
        ),
        migrations.AddField(
            model_name='poste',
            name='AUT',
            field=models.IntegerField(default=None, verbose_name='Autorisation de stockage/diffusion'),
        ),
        migrations.AddField(
            model_name='poste',
            name='CODE_POSTE',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='poste',
            name='COMM',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='poste',
            name='COMMUNE',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='gestion.COMMUNE'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poste',
            name='CP',
            field=models.IntegerField(default=None, verbose_name='Code postal'),
        ),
        migrations.AddField(
            model_name='poste',
            name='DATEFERM',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='poste',
            name='DATEOUV',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='poste',
            name='LAT',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='poste',
            name='LIEU_DIT',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='poste',
            name='LON',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='poste',
            name='MAINT',
            field=models.IntegerField(default=None, verbose_name='Code maintenance (tableau)'),
        ),
        migrations.AddField(
            model_name='poste',
            name='MEL',
            field=models.CharField(default=None, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='poste',
            name='POS',
            field=models.IntegerField(default=None, verbose_name='Personne physique(1) - Morale (2)'),
        ),
        migrations.AddField(
            model_name='poste',
            name='PROP',
            field=models.CharField(default=None, max_length=20, verbose_name='Nom du propriétaire/entreprise'),
        ),
        migrations.AddField(
            model_name='poste',
            name='REF_MF',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='poste',
            name='TEL',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='poste',
            name='TYPE',
            field=models.CharField(default=None, max_length=20, verbose_name='Modèle de station'),
        ),
        migrations.AddField(
            model_name='poste',
            name='TYPINFO',
            field=models.CharField(default=None, max_length=20, verbose_name='Type de donnees (route,agricole,pédagogique,..)'),
        ),
        migrations.AlterField(
            model_name='instan',
            name='DATJ',
            field=models.DateTimeField(verbose_name='AAAA-MM-JJ HH-MM de la mesure'),
        ),
    ]
