# Generated by Django 2.0.6 on 2018-07-10 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0014_auto_20180706_1328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='decadq',
            old_name='TXMAX',
            new_name='TNMAX',
        ),
        migrations.RenameField(
            model_name='mensq',
            old_name='TXMAX',
            new_name='TNMAX',
        ),
        migrations.AlterField(
            model_name='h',
            name='DD',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='h',
            name='DRR1',
            field=models.IntegerField(default=None, null=True, verbose_name='Durée de la précipitation en min'),
        ),
        migrations.AlterField(
            model_name='h',
            name='DXI',
            field=models.FloatField(default=None, null=True, verbose_name='Direction de FXI'),
        ),
        migrations.AlterField(
            model_name='h',
            name='DXY',
            field=models.FloatField(default=None, null=True, verbose_name='Direction de FXY'),
        ),
        migrations.AlterField(
            model_name='h',
            name='ETP',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='h',
            name='ETPN',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='h',
            name='ETPX',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='h',
            name='FF',
            field=models.FloatField(default=None, null=True, verbose_name='Force du vent moyenné sur 10min'),
        ),
        migrations.AlterField(
            model_name='h',
            name='FXI',
            field=models.FloatField(default=None, null=True, verbose_name="Rafales max de FF dans l'heure"),
        ),
        migrations.AlterField(
            model_name='h',
            name='FXY',
            field=models.FloatField(default=None, null=True, verbose_name="Valeur max de FF dans l'heure"),
        ),
        migrations.AlterField(
            model_name='h',
            name='HF',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='h',
            name='HFN',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='h',
            name='HFX',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='h',
            name='HPERMIN',
            field=models.DateTimeField(default=None, null=True, verbose_name='AAAA MM JJ HH MM de PMERMIN'),
        ),
        migrations.AlterField(
            model_name='h',
            name='HRRI',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='h',
            name='HS',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='h',
            name='HSN',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='h',
            name='HSX',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='h',
            name='HTN',
            field=models.DateTimeField(default=None, null=True, verbose_name='AAAA MM JJ HH MM de TN'),
        ),
        migrations.AlterField(
            model_name='h',
            name='HTX',
            field=models.DateTimeField(default=None, null=True, verbose_name='AAAA MM JJ HH MM de TX'),
        ),
        migrations.AlterField(
            model_name='h',
            name='HUN',
            field=models.DateTimeField(default=None, null=True, verbose_name='AAAA MM JJ HH MM de UN'),
        ),
        migrations.AlterField(
            model_name='h',
            name='HUX',
            field=models.DateTimeField(default=None, null=True, verbose_name='AAAA MM JJ HH MM de UX'),
        ),
        migrations.AlterField(
            model_name='h',
            name='HXI',
            field=models.DateTimeField(default=None, null=True, verbose_name='AAAA MM JJ HH MM de FXI'),
        ),
        migrations.AlterField(
            model_name='h',
            name='HXY',
            field=models.DateTimeField(default=None, null=True, verbose_name='AAAA MM JJ HH MM de FXY'),
        ),
        migrations.AlterField(
            model_name='h',
            name='IC',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='h',
            name='PMER',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='h',
            name='PMERMIN',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='h',
            name='RAD',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='h',
            name='RR1',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='h',
            name='RRI',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='h',
            name='STATUS_DRR1',
            field=models.IntegerField(default=None, null=True, verbose_name='1 - Relevé manuel, 2 - Relevé automatique'),
        ),
        migrations.AlterField(
            model_name='h',
            name='T',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='h',
            name='TD',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='h',
            name='TN',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='h',
            name='TS',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='h',
            name='TSN',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='h',
            name='TSX',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='h',
            name='TX',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='h',
            name='U',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='h',
            name='UN',
            field=models.FloatField(default=None, null=True, verbose_name="Humidite minimale dans l'heure"),
        ),
        migrations.AlterField(
            model_name='h',
            name='UV',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='h',
            name='UX',
            field=models.FloatField(default=None, null=True, verbose_name="Humidite maximale dans l'heure"),
        ),
        migrations.AlterField(
            model_name='h',
            name='WINDCHILL',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='poste',
            name='CODE_POSTE',
            field=models.CharField(default=None, max_length=15),
        ),
        migrations.AlterField(
            model_name='poste',
            name='NOM',
            field=models.CharField(default=None, max_length=50, verbose_name='Nom du poste (ex : NDLP)'),
        ),
        migrations.AlterField(
            model_name='q',
            name='DG',
            field=models.IntegerField(default=None, null=True, verbose_name='Duree du gel en min'),
        ),
        migrations.AlterField(
            model_name='q',
            name='DRR',
            field=models.FloatField(default=None, null=True, verbose_name='Durée de la précipitation en min'),
        ),
        migrations.AlterField(
            model_name='q',
            name='DXI',
            field=models.FloatField(default=None, null=True, verbose_name='Direction de FXI'),
        ),
        migrations.AlterField(
            model_name='q',
            name='DXY',
            field=models.FloatField(default=None, null=True, verbose_name='Direction de FXY'),
        ),
        migrations.AlterField(
            model_name='q',
            name='ETPM',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='q',
            name='FXI',
            field=models.FloatField(default=None, null=True, verbose_name='Rafales max de FF dans la journee'),
        ),
        migrations.AlterField(
            model_name='q',
            name='FXY',
            field=models.FloatField(default=None, null=True, verbose_name='Valeur max de FF dans la journee'),
        ),
        migrations.AlterField(
            model_name='q',
            name='HFM',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='q',
            name='HFMN',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='q',
            name='HFMX',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='q',
            name='HSM',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='q',
            name='HSMN',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='q',
            name='HSMX',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='q',
            name='HTN',
            field=models.DateTimeField(default=None, null=True, verbose_name='AAAA MM JJ HH MM de TN'),
        ),
        migrations.AlterField(
            model_name='q',
            name='HTX',
            field=models.DateTimeField(default=None, null=True, verbose_name='AAAA MM JJ HH MM de TX'),
        ),
        migrations.AlterField(
            model_name='q',
            name='HUN',
            field=models.DateTimeField(default=None, null=True, verbose_name='AAAA MM JJ HH MM de UN'),
        ),
        migrations.AlterField(
            model_name='q',
            name='HUX',
            field=models.DateTimeField(default=None, null=True, verbose_name='AAAA MM JJ HH MM de UX'),
        ),
        migrations.AlterField(
            model_name='q',
            name='HXI',
            field=models.DateTimeField(default=None, null=True, verbose_name='AAAA MM JJ HH MM de FXI'),
        ),
        migrations.AlterField(
            model_name='q',
            name='HXY',
            field=models.DateTimeField(default=None, null=True, verbose_name='AAAA MM JJ HH MM de FXY'),
        ),
        migrations.AlterField(
            model_name='q',
            name='INST',
            field=models.IntegerField(default=None, null=True, verbose_name="Duree d'insolation quotidienne (min)"),
        ),
        migrations.AlterField(
            model_name='q',
            name='PMERM',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='q',
            name='PMERMIN',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='q',
            name='RR',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='q',
            name='STATUS_DRR',
            field=models.IntegerField(default=None, null=True, verbose_name='1 - Relevé manuel, 2 - Relevé automatique'),
        ),
        migrations.AlterField(
            model_name='q',
            name='TM',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='q',
            name='TN',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='q',
            name='TS',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='q',
            name='TSN',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='q',
            name='TSX',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='q',
            name='TX',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='q',
            name='UM',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='q',
            name='UN',
            field=models.FloatField(default=None, null=True, verbose_name='Humidite minimale dans la journee'),
        ),
        migrations.AlterField(
            model_name='q',
            name='UX',
            field=models.FloatField(default=None, null=True, verbose_name="Humidite maximale dans l'heure"),
        ),
    ]
