# Generated by Django 2.0.6 on 2018-07-11 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0015_auto_20180710_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decadq',
            name='DXIAB',
            field=models.FloatField(default=None, null=True, verbose_name='Direction de la rafale maxi de la décade'),
        ),
        migrations.AlterField(
            model_name='decadq',
            name='DXYAB',
            field=models.FloatField(default=None, null=True, verbose_name='Direction du FXYAB de la decade'),
        ),
        migrations.AlterField(
            model_name='decadq',
            name='FXIAB',
            field=models.FloatField(default=None, null=True, verbose_name='Rafale maxi de la décade'),
        ),
        migrations.AlterField(
            model_name='decadq',
            name='FXIDAT',
            field=models.DateTimeField(default=None, null=True, verbose_name='Date la rafale maxi de la decade'),
        ),
        migrations.AlterField(
            model_name='decadq',
            name='FXYAB',
            field=models.FloatField(default=None, null=True, verbose_name='FXY max de la decade'),
        ),
        migrations.AlterField(
            model_name='decadq',
            name='FXYABDAT',
            field=models.DateTimeField(default=None, null=True, verbose_name='Date du FXYAB de la decade'),
        ),
        migrations.AlterField(
            model_name='decadq',
            name='HFM',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='decadq',
            name='HFN',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='decadq',
            name='HFX',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='decadq',
            name='HSM',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='decadq',
            name='HSN',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='decadq',
            name='HSX',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='decadq',
            name='INST',
            field=models.IntegerField(default=None, null=True, verbose_name="Duree d'insolation quotidienne moyenne (min, default = None)"),
        ),
        migrations.AlterField(
            model_name='decadq',
            name='NBJFF10',
            field=models.IntegerField(default=None, null=True, verbose_name='Nombre de jours ou FF est sup à 10m/s'),
        ),
        migrations.AlterField(
            model_name='decadq',
            name='NBJFF16',
            field=models.IntegerField(default=None, null=True, verbose_name='Nombre de jours ou FF est sup à 16m/s'),
        ),
        migrations.AlterField(
            model_name='decadq',
            name='NBJFF28',
            field=models.IntegerField(default=None, null=True, verbose_name='Nombre de jours ou FF est sup à 28m/s'),
        ),
        migrations.AlterField(
            model_name='decadq',
            name='NBJFXY10',
            field=models.IntegerField(default=None, null=True, verbose_name='Nombre de jours ou FXY est sup à 10m/s'),
        ),
        migrations.AlterField(
            model_name='decadq',
            name='NBJFXY15',
            field=models.IntegerField(default=None, null=True, verbose_name='Nombre de jours ou FXY est sup à 15m/s'),
        ),
        migrations.AlterField(
            model_name='decadq',
            name='NBJFXY8',
            field=models.IntegerField(default=None, null=True, verbose_name='Nombre de jours ou FXY est sup à 8m/s'),
        ),
        migrations.AlterField(
            model_name='decadq',
            name='NBJGELEE',
            field=models.IntegerField(default=None, null=True, verbose_name='Nombre de jours ou la TN est inf à 0'),
        ),
        migrations.AlterField(
            model_name='decadq',
            name='NBJRR1',
            field=models.IntegerField(default=None, null=True, verbose_name='Nb de jours RR sup à 1mm'),
        ),
        migrations.AlterField(
            model_name='decadq',
            name='NBJRR10',
            field=models.IntegerField(default=None, null=True, verbose_name='Nb de jours RR sup à 10mm'),
        ),
        migrations.AlterField(
            model_name='decadq',
            name='NBJRR100',
            field=models.IntegerField(null=True, verbose_name='Nb de jours RR sup à 100mm, default = None'),
        ),
        migrations.AlterField(
            model_name='decadq',
            name='NBJRR30',
            field=models.IntegerField(default=None, null=True, verbose_name='Nb de jours RR sup à 30mm'),
        ),
        migrations.AlterField(
            model_name='decadq',
            name='NBJRR5',
            field=models.IntegerField(default=None, null=True, verbose_name='Nb de jours RR sup à 5mm'),
        ),
        migrations.AlterField(
            model_name='decadq',
            name='NBJRR50',
            field=models.IntegerField(default=None, null=True, verbose_name='Nb de jours RR sup à 50mm'),
        ),
        migrations.AlterField(
            model_name='decadq',
            name='NBJTN5',
            field=models.IntegerField(default=None, null=True, verbose_name='Nombre de jours ou la TN est inf à -5'),
        ),
        migrations.AlterField(
            model_name='decadq',
            name='NBJTNI10',
            field=models.IntegerField(default=None, null=True, verbose_name='Nombre de jours ou la TN est inf à 10'),
        ),
        migrations.AlterField(
            model_name='decadq',
            name='NBJTNI15',
            field=models.IntegerField(default=None, null=True, verbose_name='Nombre de jours ou la TN est inf à 15'),
        ),
        migrations.AlterField(
            model_name='decadq',
            name='NBJTNI20',
            field=models.IntegerField(default=None, null=True, verbose_name='Nombre de jours ou la TN est inf à 20'),
        ),
        migrations.AlterField(
            model_name='decadq',
            name='NBJTNS20',
            field=models.IntegerField(default=None, null=True, verbose_name='Nombre de jours ou la TN est sup à 20'),
        ),
        migrations.AlterField(
            model_name='decadq',
            name='NBJTNS25',
            field=models.IntegerField(default=None, null=True, verbose_name='Nombre de jours ou la TN est sup à 25'),
        ),
        migrations.AlterField(
            model_name='decadq',
            name='NBJTX0',
            field=models.IntegerField(default=None, null=True, verbose_name='Nombre de jours ou la TX est inf à 0'),
        ),
        migrations.AlterField(
            model_name='decadq',
            name='NBJTX25',
            field=models.IntegerField(default=None, null=True, verbose_name='Nombre de jours ou la TX est sup à 25'),
        ),
        migrations.AlterField(
            model_name='decadq',
            name='NBJTX30',
            field=models.IntegerField(default=None, null=True, verbose_name='Nombre de jours ou la TX est sup à 30'),
        ),
        migrations.AlterField(
            model_name='decadq',
            name='NBJTX32',
            field=models.IntegerField(default=None, null=True, verbose_name='Nombre de jours ou la TX est sup à 32'),
        ),
        migrations.AlterField(
            model_name='decadq',
            name='NBJTX35',
            field=models.IntegerField(default=None, null=True, verbose_name='Nombre de jours ou la TX est sup à 35'),
        ),
        migrations.AlterField(
            model_name='decadq',
            name='NBJTXI20',
            field=models.IntegerField(default=None, null=True, verbose_name='Nombre de jours ou la TX est inf à 20'),
        ),
        migrations.AlterField(
            model_name='decadq',
            name='NBJTXI27',
            field=models.IntegerField(default=None, null=True, verbose_name='Nombre de jours ou la TX est inf à 27'),
        ),
        migrations.AlterField(
            model_name='decadq',
            name='NUM_DECADE',
            field=models.IntegerField(default=None, null=True, verbose_name='Numero de la decade'),
        ),
        migrations.AlterField(
            model_name='decadq',
            name='PMERM',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='decadq',
            name='PMERMINAB',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='decadq',
            name='PMERMINABDAT',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='decadq',
            name='RR',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='decadq',
            name='RRAB',
            field=models.FloatField(default=None, null=True, verbose_name='Precipitation maxi en 24h'),
        ),
        migrations.AlterField(
            model_name='decadq',
            name='RRABDAT',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='decadq',
            name='STATUS_DRR',
            field=models.IntegerField(default=None, null=True, verbose_name='1 - Relevé manuel, 2 - Relevé automatique'),
        ),
        migrations.AlterField(
            model_name='decadq',
            name='STATUS_RRAB',
            field=models.IntegerField(default=None, null=True, verbose_name='1 - Relevé manuel, 2 - Relevé automatique'),
        ),
        migrations.AlterField(
            model_name='decadq',
            name='TN',
            field=models.FloatField(default=None, null=True, verbose_name='Moyenne des TN de la decade'),
        ),
        migrations.AlterField(
            model_name='decadq',
            name='TNAB',
            field=models.FloatField(default=None, null=True, verbose_name='TN min de la decade'),
        ),
        migrations.AlterField(
            model_name='decadq',
            name='TNDAT',
            field=models.DateTimeField(default=None, null=True, verbose_name='Date de la TN min de la decade'),
        ),
        migrations.AlterField(
            model_name='decadq',
            name='TNMAX',
            field=models.FloatField(default=None, null=True, verbose_name='TN max de la decade'),
        ),
        migrations.AlterField(
            model_name='decadq',
            name='TNMAXDAT',
            field=models.DateTimeField(default=None, null=True, verbose_name='Date de la TN max de la decade'),
        ),
        migrations.AlterField(
            model_name='decadq',
            name='TSM',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='decadq',
            name='TSN',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='decadq',
            name='TSX',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='decadq',
            name='TX',
            field=models.FloatField(default=None, null=True, verbose_name='Moyenne des TX de la decade'),
        ),
        migrations.AlterField(
            model_name='decadq',
            name='TXAB',
            field=models.FloatField(default=None, null=True, verbose_name='TX max de la decade'),
        ),
        migrations.AlterField(
            model_name='decadq',
            name='TXABDAT',
            field=models.DateTimeField(default=None, null=True, verbose_name='Date de la TX de la decade'),
        ),
        migrations.AlterField(
            model_name='decadq',
            name='TXMIN',
            field=models.FloatField(default=None, null=True, verbose_name='TX min de la decade'),
        ),
        migrations.AlterField(
            model_name='decadq',
            name='TXMINDAT',
            field=models.DateTimeField(default=None, null=True, verbose_name='Date de la TX min de la decade'),
        ),
        migrations.AlterField(
            model_name='decadq',
            name='UMM',
            field=models.FloatField(default=None, null=True, verbose_name='Moyenne des humidites relatives de la decade'),
        ),
        migrations.AlterField(
            model_name='decadq',
            name='UNAB',
            field=models.FloatField(default=None, null=True, verbose_name='Humidite relative minimale de la decade'),
        ),
        migrations.AlterField(
            model_name='decadq',
            name='UNABDAT',
            field=models.DateTimeField(default=None, null=True, verbose_name="Date de l'Humidite relative minimale de la decade"),
        ),
        migrations.AlterField(
            model_name='decadq',
            name='UXAB',
            field=models.FloatField(default=None, null=True, verbose_name='Humidite relative maximale de la decade'),
        ),
        migrations.AlterField(
            model_name='decadq',
            name='UXABDAT',
            field=models.DateTimeField(default=None, null=True, verbose_name="Date de l'humidite relative maximale de la decade"),
        ),
    ]
