# Generated by Django 2.0.6 on 2018-07-11 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0016_auto_20180711_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='COMM',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='DATDEB',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='DATFIN',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='HAUTEUR',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='MODELE',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Version et modele du capteur'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='PASDETEMPS',
            field=models.FloatField(blank=True, null=True, verbose_name='Intervalle de mesure en s'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='PRECISION',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='QUALITE',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name="Qualite du site d'installation (voir classification)"),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='SEUILMAX',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='SEUILMIN',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='TYPE_TERRAIN',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name="Type de terrain sur l'implantation du capteur"),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='UNITE',
            field=models.CharField(blank=True, help_text='a', max_length=10, null=True, verbose_name='Unite de mesure'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='VENTILATION',
            field=models.IntegerField(blank=True, null=True, verbose_name='1 si capteur ventile, 0 sinon'),
        ),
    ]
