# Generated by Django 2.0.6 on 2018-07-11 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0017_auto_20180711_1010'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lien', models.FileField(upload_to='data/')),
                ('POSTE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.POSTE')),
            ],
        ),
        migrations.AlterField(
            model_name='instrument',
            name='UNITE',
            field=models.CharField(blank=True, help_text='a<br/>b', max_length=10, null=True, verbose_name='Unite de mesure'),
        ),
    ]
