# Generated by Django 2.0.6 on 2018-07-11 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0018_auto_20180711_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='POSTE',
        ),
        migrations.AddField(
            model_name='file',
            name='CODE_POSTE',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='poste',
            name='MAINT',
            field=models.IntegerField(default=None, null=True, verbose_name='Code maintenance (tableau)'),
        ),
    ]
