# Generated by Django 2.0.6 on 2018-07-11 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0019_auto_20180711_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lien', models.FileField(upload_to='data/')),
            ],
        ),
        migrations.DeleteModel(
            name='File',
        ),
        migrations.AlterField(
            model_name='poste',
            name='CODE_POSTE',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='files',
            name='POSTE',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.POSTE'),
        ),
    ]
