# Generated by Django 2.0.6 on 2018-07-23 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0022_auto_20180723_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decadq',
            name='DXIAB',
            field=models.FloatField(default=float("nan"), null=True, verbose_name='Direction de la rafale maxi de la décade'),
        ),
        migrations.AlterField(
            model_name='decadq',
            name='DXYAB',
            field=models.FloatField(default=float("nan"), null=True, verbose_name='Direction du FXYAB de la decade'),
        ),
        migrations.AlterField(
            model_name='decadq',
            name='FXIAB',
            field=models.FloatField(default=float("nan"), null=True, verbose_name='Rafale maxi de la décade'),
        ),
        migrations.AlterField(
            model_name='decadq',
            name='FXIDAT',
            field=models.DateTimeField(default=float("nan"), null=True, verbose_name='Date la rafale maxi de la decade'),
        ),
        migrations.AlterField(
            model_name='decadq',
            name='FXYAB',
            field=models.FloatField(default=float("nan"), null=True, verbose_name='FXY max de la decade'),
        ),
        migrations.AlterField(
            model_name='decadq',
            name='FXYABDAT',
            field=models.DateTimeField(default=float("nan"), null=True, verbose_name='Date du FXYAB de la decade'),
        ),
        migrations.AlterField(
            model_name='decadq',
            name='HFM',
            field=models.FloatField(default=float("nan"), null=True),
        ),
        migrations.AlterField(
            model_name='decadq',
            name='HFN',
            field=models.FloatField(default=float("nan"), null=True),
        ),
        migrations.AlterField(
            model_name='decadq',
            name='HFX',
            field=models.FloatField(default=float("nan"), null=True),
        ),
        migrations.AlterField(
            model_name='decadq',
            name='HSM',
            field=models.FloatField(default=float("nan"), null=True),
        ),
        migrations.AlterField(
            model_name='decadq',
            name='HSN',
            field=models.FloatField(default=float("nan"), null=True),
        ),
        migrations.AlterField(
            model_name='decadq',
            name='HSX',
            field=models.FloatField(default=float("nan"), null=True),
        ),
        migrations.AlterField(
            model_name='decadq',
            name='INST',
            field=models.IntegerField(default=float("nan"), null=True, verbose_name="Duree d'insolation quotidienne moyenne (min, default = math.nan)"),
        ),
        migrations.AlterField(
            model_name='decadq',
            name='NBJFF10',
            field=models.IntegerField(default=float("nan"), null=True, verbose_name='Nombre de jours ou FF est sup à 10m/s'),
        ),
        migrations.AlterField(
            model_name='decadq',
            name='NBJFF16',
            field=models.IntegerField(default=float("nan"), null=True, verbose_name='Nombre de jours ou FF est sup à 16m/s'),
        ),
        migrations.AlterField(
            model_name='decadq',
            name='NBJFF28',
            field=models.IntegerField(default=float("nan"), null=True, verbose_name='Nombre de jours ou FF est sup à 28m/s'),
        ),
        migrations.AlterField(
            model_name='decadq',
            name='NBJFXY10',
            field=models.IntegerField(default=float("nan"), null=True, verbose_name='Nombre de jours ou FXY est sup à 10m/s'),
        ),
        migrations.AlterField(
            model_name='decadq',
            name='NBJFXY15',
            field=models.IntegerField(default=float("nan"), null=True, verbose_name='Nombre de jours ou FXY est sup à 15m/s'),
        ),
        migrations.AlterField(
            model_name='decadq',
            name='NBJFXY8',
            field=models.IntegerField(default=float("nan"), null=True, verbose_name='Nombre de jours ou FXY est sup à 8m/s'),
        ),
        migrations.AlterField(
            model_name='decadq',
            name='NBJGELEE',
            field=models.IntegerField(default=float("nan"), null=True, verbose_name='Nombre de jours ou la TN est inf à 0'),
        ),
        migrations.AlterField(
            model_name='decadq',
            name='NBJRR1',
            field=models.IntegerField(default=float("nan"), null=True, verbose_name='Nb de jours RR sup à 1mm'),
        ),
        migrations.AlterField(
            model_name='decadq',
            name='NBJRR10',
            field=models.IntegerField(default=float("nan"), null=True, verbose_name='Nb de jours RR sup à 10mm'),
        ),
        migrations.AlterField(
            model_name='decadq',
            name='NBJRR30',
            field=models.IntegerField(default=float("nan"), null=True, verbose_name='Nb de jours RR sup à 30mm'),
        ),
        migrations.AlterField(
            model_name='decadq',
            name='NBJRR5',
            field=models.IntegerField(default=float("nan"), null=True, verbose_name='Nb de jours RR sup à 5mm'),
        ),
        migrations.AlterField(
            model_name='decadq',
            name='NBJRR50',
            field=models.IntegerField(default=float("nan"), null=True, verbose_name='Nb de jours RR sup à 50mm'),
        ),
        migrations.AlterField(
            model_name='decadq',
            name='NBJTN5',
            field=models.IntegerField(default=float("nan"), null=True, verbose_name='Nombre de jours ou la TN est inf à -5'),
        ),
        migrations.AlterField(
            model_name='decadq',
            name='NBJTNI10',
            field=models.IntegerField(default=float("nan"), null=True, verbose_name='Nombre de jours ou la TN est inf à 10'),
        ),
        migrations.AlterField(
            model_name='decadq',
            name='NBJTNI15',
            field=models.IntegerField(default=float("nan"), null=True, verbose_name='Nombre de jours ou la TN est inf à 15'),
        ),
        migrations.AlterField(
            model_name='decadq',
            name='NBJTNI20',
            field=models.IntegerField(default=float("nan"), null=True, verbose_name='Nombre de jours ou la TN est inf à 20'),
        ),
        migrations.AlterField(
            model_name='decadq',
            name='NBJTNS20',
            field=models.IntegerField(default=float("nan"), null=True, verbose_name='Nombre de jours ou la TN est sup à 20'),
        ),
        migrations.AlterField(
            model_name='decadq',
            name='NBJTNS25',
            field=models.IntegerField(default=float("nan"), null=True, verbose_name='Nombre de jours ou la TN est sup à 25'),
        ),
        migrations.AlterField(
            model_name='decadq',
            name='NBJTX0',
            field=models.IntegerField(default=float("nan"), null=True, verbose_name='Nombre de jours ou la TX est inf à 0'),
        ),
        migrations.AlterField(
            model_name='decadq',
            name='NBJTX25',
            field=models.IntegerField(default=float("nan"), null=True, verbose_name='Nombre de jours ou la TX est sup à 25'),
        ),
        migrations.AlterField(
            model_name='decadq',
            name='NBJTX30',
            field=models.IntegerField(default=float("nan"), null=True, verbose_name='Nombre de jours ou la TX est sup à 30'),
        ),
        migrations.AlterField(
            model_name='decadq',
            name='NBJTX32',
            field=models.IntegerField(default=float("nan"), null=True, verbose_name='Nombre de jours ou la TX est sup à 32'),
        ),
        migrations.AlterField(
            model_name='decadq',
            name='NBJTX35',
            field=models.IntegerField(default=float("nan"), null=True, verbose_name='Nombre de jours ou la TX est sup à 35'),
        ),
        migrations.AlterField(
            model_name='decadq',
            name='NBJTXI20',
            field=models.IntegerField(default=float("nan"), null=True, verbose_name='Nombre de jours ou la TX est inf à 20'),
        ),
        migrations.AlterField(
            model_name='decadq',
            name='NBJTXI27',
            field=models.IntegerField(default=float("nan"), null=True, verbose_name='Nombre de jours ou la TX est inf à 27'),
        ),
        migrations.AlterField(
            model_name='decadq',
            name='NUM_DECADE',
            field=models.IntegerField(default=float("nan"), null=True, verbose_name='Numero de la decade'),
        ),
        migrations.AlterField(
            model_name='decadq',
            name='PMERM',
            field=models.FloatField(default=float("nan"), null=True),
        ),
        migrations.AlterField(
            model_name='decadq',
            name='PMERMINAB',
            field=models.FloatField(default=float("nan"), null=True),
        ),
        migrations.AlterField(
            model_name='decadq',
            name='PMERMINABDAT',
            field=models.DateTimeField(default=float("nan"), null=True),
        ),
        migrations.AlterField(
            model_name='decadq',
            name='RR',
            field=models.FloatField(default=float("nan"), null=True),
        ),
        migrations.AlterField(
            model_name='decadq',
            name='RRAB',
            field=models.FloatField(default=float("nan"), null=True, verbose_name='Precipitation maxi en 24h'),
        ),
        migrations.AlterField(
            model_name='decadq',
            name='RRABDAT',
            field=models.DateTimeField(default=float("nan"), null=True),
        ),
        migrations.AlterField(
            model_name='decadq',
            name='STATUS_DRR',
            field=models.IntegerField(default=float("nan"), null=True, verbose_name='1 - Relevé manuel, 2 - Relevé automatique'),
        ),
        migrations.AlterField(
            model_name='decadq',
            name='STATUS_RRAB',
            field=models.IntegerField(default=float("nan"), null=True, verbose_name='1 - Relevé manuel, 2 - Relevé automatique'),
        ),
        migrations.AlterField(
            model_name='decadq',
            name='TN',
            field=models.FloatField(default=float("nan"), null=True, verbose_name='Moyenne des TN de la decade'),
        ),
        migrations.AlterField(
            model_name='decadq',
            name='TNAB',
            field=models.FloatField(default=float("nan"), null=True, verbose_name='TN min de la decade'),
        ),
        migrations.AlterField(
            model_name='decadq',
            name='TNDAT',
            field=models.DateTimeField(default=float("nan"), null=True, verbose_name='Date de la TN min de la decade'),
        ),
        migrations.AlterField(
            model_name='decadq',
            name='TNMAX',
            field=models.FloatField(default=float("nan"), null=True, verbose_name='TN max de la decade'),
        ),
        migrations.AlterField(
            model_name='decadq',
            name='TNMAXDAT',
            field=models.DateTimeField(default=float("nan"), null=True, verbose_name='Date de la TN max de la decade'),
        ),
        migrations.AlterField(
            model_name='decadq',
            name='TSM',
            field=models.FloatField(default=float("nan"), null=True),
        ),
        migrations.AlterField(
            model_name='decadq',
            name='TSN',
            field=models.FloatField(default=float("nan"), null=True),
        ),
        migrations.AlterField(
            model_name='decadq',
            name='TSX',
            field=models.FloatField(default=float("nan"), null=True),
        ),
        migrations.AlterField(
            model_name='decadq',
            name='TX',
            field=models.FloatField(default=float("nan"), null=True, verbose_name='Moyenne des TX de la decade'),
        ),
        migrations.AlterField(
            model_name='decadq',
            name='TXAB',
            field=models.FloatField(default=float("nan"), null=True, verbose_name='TX max de la decade'),
        ),
        migrations.AlterField(
            model_name='decadq',
            name='TXABDAT',
            field=models.DateTimeField(default=float("nan"), null=True, verbose_name='Date de la TX de la decade'),
        ),
        migrations.AlterField(
            model_name='decadq',
            name='TXMIN',
            field=models.FloatField(default=float("nan"), null=True, verbose_name='TX min de la decade'),
        ),
        migrations.AlterField(
            model_name='decadq',
            name='TXMINDAT',
            field=models.DateTimeField(default=float("nan"), null=True, verbose_name='Date de la TX min de la decade'),
        ),
        migrations.AlterField(
            model_name='decadq',
            name='UMM',
            field=models.FloatField(default=float("nan"), null=True, verbose_name='Moyenne des humidites relatives de la decade'),
        ),
        migrations.AlterField(
            model_name='decadq',
            name='UNAB',
            field=models.FloatField(default=float("nan"), null=True, verbose_name='Humidite relative minimale de la decade'),
        ),
        migrations.AlterField(
            model_name='decadq',
            name='UNABDAT',
            field=models.DateTimeField(default=float("nan"), null=True, verbose_name="Date de l'Humidite relative minimale de la decade"),
        ),
        migrations.AlterField(
            model_name='decadq',
            name='UXAB',
            field=models.FloatField(default=float("nan"), null=True, verbose_name='Humidite relative maximale de la decade'),
        ),
        migrations.AlterField(
            model_name='decadq',
            name='UXABDAT',
            field=models.DateTimeField(default=float("nan"), null=True, verbose_name="Date de l'humidite relative maximale de la decade"),
        ),
        migrations.AlterField(
            model_name='h',
            name='DD',
            field=models.FloatField(default=float("nan"), null=True),
        ),
        migrations.AlterField(
            model_name='h',
            name='DRR1',
            field=models.IntegerField(default=float("nan"), null=True, verbose_name='Durée de la précipitation en min'),
        ),
        migrations.AlterField(
            model_name='h',
            name='DXI',
            field=models.FloatField(default=float("nan"), null=True, verbose_name='Direction de FXI'),
        ),
        migrations.AlterField(
            model_name='h',
            name='DXY',
            field=models.FloatField(default=float("nan"), null=True, verbose_name='Direction de FXY'),
        ),
        migrations.AlterField(
            model_name='h',
            name='ETP',
            field=models.FloatField(default=float("nan"), null=True),
        ),
        migrations.AlterField(
            model_name='h',
            name='ETPN',
            field=models.FloatField(default=float("nan"), null=True),
        ),
        migrations.AlterField(
            model_name='h',
            name='ETPX',
            field=models.FloatField(default=float("nan"), null=True),
        ),
        migrations.AlterField(
            model_name='h',
            name='FF',
            field=models.FloatField(default=float("nan"), null=True, verbose_name='Force du vent moyenné sur 10min'),
        ),
        migrations.AlterField(
            model_name='h',
            name='FXI',
            field=models.FloatField(default=float("nan"), null=True, verbose_name="Rafales max de FF dans l'heure"),
        ),
        migrations.AlterField(
            model_name='h',
            name='FXY',
            field=models.FloatField(default=float("nan"), null=True, verbose_name="Valeur max de FF dans l'heure"),
        ),
        migrations.AlterField(
            model_name='h',
            name='HF',
            field=models.FloatField(default=float("nan"), null=True),
        ),
        migrations.AlterField(
            model_name='h',
            name='HFN',
            field=models.FloatField(default=float("nan"), null=True),
        ),
        migrations.AlterField(
            model_name='h',
            name='HFX',
            field=models.FloatField(default=float("nan"), null=True),
        ),
        migrations.AlterField(
            model_name='h',
            name='HPERMIN',
            field=models.DateTimeField(default=float("nan"), null=True, verbose_name='AAAA MM JJ HH MM de PMERMIN'),
        ),
        migrations.AlterField(
            model_name='h',
            name='HRRI',
            field=models.DateTimeField(default=float("nan"), null=True),
        ),
        migrations.AlterField(
            model_name='h',
            name='HS',
            field=models.FloatField(default=float("nan"), null=True),
        ),
        migrations.AlterField(
            model_name='h',
            name='HSN',
            field=models.FloatField(default=float("nan"), null=True),
        ),
        migrations.AlterField(
            model_name='h',
            name='HSX',
            field=models.FloatField(default=float("nan"), null=True),
        ),
        migrations.AlterField(
            model_name='h',
            name='HTN',
            field=models.DateTimeField(default=float("nan"), null=True, verbose_name='AAAA MM JJ HH MM de TN'),
        ),
        migrations.AlterField(
            model_name='h',
            name='HTX',
            field=models.DateTimeField(default=float("nan"), null=True, verbose_name='AAAA MM JJ HH MM de TX'),
        ),
        migrations.AlterField(
            model_name='h',
            name='HUN',
            field=models.DateTimeField(default=float("nan"), null=True, verbose_name='AAAA MM JJ HH MM de UN'),
        ),
        migrations.AlterField(
            model_name='h',
            name='HUX',
            field=models.DateTimeField(default=float("nan"), null=True, verbose_name='AAAA MM JJ HH MM de UX'),
        ),
        migrations.AlterField(
            model_name='h',
            name='HXI',
            field=models.DateTimeField(default=float("nan"), null=True, verbose_name='AAAA MM JJ HH MM de FXI'),
        ),
        migrations.AlterField(
            model_name='h',
            name='HXY',
            field=models.DateTimeField(default=float("nan"), null=True, verbose_name='AAAA MM JJ HH MM de FXY'),
        ),
        migrations.AlterField(
            model_name='h',
            name='IC',
            field=models.FloatField(default=float("nan"), null=True),
        ),
        migrations.AlterField(
            model_name='h',
            name='PMER',
            field=models.FloatField(default=float("nan"), null=True),
        ),
        migrations.AlterField(
            model_name='h',
            name='PMERMIN',
            field=models.FloatField(default=float("nan"), null=True),
        ),
        migrations.AlterField(
            model_name='h',
            name='RAD',
            field=models.FloatField(default=float("nan"), null=True),
        ),
        migrations.AlterField(
            model_name='h',
            name='RR1',
            field=models.FloatField(default=float("nan"), null=True),
        ),
        migrations.AlterField(
            model_name='h',
            name='RRI',
            field=models.FloatField(default=float("nan"), null=True),
        ),
        migrations.AlterField(
            model_name='h',
            name='STATUS_DRR1',
            field=models.IntegerField(default=float("nan"), null=True, verbose_name='1 - Relevé manuel, 2 - Relevé automatique'),
        ),
        migrations.AlterField(
            model_name='h',
            name='T',
            field=models.FloatField(default=float("nan"), null=True),
        ),
        migrations.AlterField(
            model_name='h',
            name='TD',
            field=models.FloatField(default=float("nan"), null=True),
        ),
        migrations.AlterField(
            model_name='h',
            name='TN',
            field=models.FloatField(default=float("nan"), null=True),
        ),
        migrations.AlterField(
            model_name='h',
            name='TS',
            field=models.FloatField(default=float("nan"), null=True),
        ),
        migrations.AlterField(
            model_name='h',
            name='TSN',
            field=models.FloatField(default=float("nan"), null=True),
        ),
        migrations.AlterField(
            model_name='h',
            name='TSX',
            field=models.FloatField(default=float("nan"), null=True),
        ),
        migrations.AlterField(
            model_name='h',
            name='TX',
            field=models.FloatField(default=float("nan"), null=True),
        ),
        migrations.AlterField(
            model_name='h',
            name='U',
            field=models.FloatField(default=float("nan"), null=True),
        ),
        migrations.AlterField(
            model_name='h',
            name='UN',
            field=models.FloatField(default=float("nan"), null=True, verbose_name="Humidite minimale dans l'heure"),
        ),
        migrations.AlterField(
            model_name='h',
            name='UV',
            field=models.IntegerField(default=float("nan"), null=True),
        ),
        migrations.AlterField(
            model_name='h',
            name='UX',
            field=models.FloatField(default=float("nan"), null=True, verbose_name="Humidite maximale dans l'heure"),
        ),
        migrations.AlterField(
            model_name='h',
            name='WINDCHILL',
            field=models.FloatField(default=float("nan"), null=True),
        ),
        migrations.AlterField(
            model_name='instan',
            name='DD',
            field=models.FloatField(default=float("nan"), null=True),
        ),
        migrations.AlterField(
            model_name='instan',
            name='DXI',
            field=models.FloatField(default=float("nan"), null=True),
        ),
        migrations.AlterField(
            model_name='instan',
            name='ETP',
            field=models.FloatField(default=float("nan"), null=True, verbose_name='Evapotranspiration'),
        ),
        migrations.AlterField(
            model_name='instan',
            name='FF',
            field=models.FloatField(default=float("nan"), null=True),
        ),
        migrations.AlterField(
            model_name='instan',
            name='FXI',
            field=models.FloatField(default=float("nan"), null=True),
        ),
        migrations.AlterField(
            model_name='instan',
            name='HF',
            field=models.FloatField(default=float("nan"), null=True, verbose_name='Humidite du feuillage'),
        ),
        migrations.AlterField(
            model_name='instan',
            name='HS',
            field=models.FloatField(default=float("nan"), null=True, verbose_name='Humidite du sol'),
        ),
        migrations.AlterField(
            model_name='instan',
            name='IC',
            field=models.FloatField(default=float("nan"), null=True, verbose_name='Indice de chaleur'),
        ),
        migrations.AlterField(
            model_name='instan',
            name='PMER',
            field=models.FloatField(default=float("nan"), null=True),
        ),
        migrations.AlterField(
            model_name='instan',
            name='RAD',
            field=models.FloatField(default=float("nan"), null=True),
        ),
        migrations.AlterField(
            model_name='instan',
            name='RR',
            field=models.FloatField(default=float("nan"), null=True),
        ),
        migrations.AlterField(
            model_name='instan',
            name='RRI',
            field=models.FloatField(default=float("nan"), null=True, verbose_name='Intensité max des precipitations'),
        ),
        migrations.AlterField(
            model_name='instan',
            name='T',
            field=models.FloatField(default=float("nan"), null=True),
        ),
        migrations.AlterField(
            model_name='instan',
            name='TD',
            field=models.FloatField(default=float("nan"), null=True),
        ),
        migrations.AlterField(
            model_name='instan',
            name='TS',
            field=models.FloatField(default=float("nan"), null=True, verbose_name='Temperature du sol'),
        ),
        migrations.AlterField(
            model_name='instan',
            name='U',
            field=models.FloatField(default=float("nan"), null=True),
        ),
        migrations.AlterField(
            model_name='instan',
            name='UV',
            field=models.FloatField(default=float("nan"), null=True, verbose_name='Indice UV'),
        ),
        migrations.AlterField(
            model_name='instan',
            name='WINDCHILL',
            field=models.FloatField(default=float("nan"), null=True),
        ),
        migrations.AlterField(
            model_name='mensq',
            name='DXIAB',
            field=models.FloatField(default=float("nan"), null=True, verbose_name='Direction de la rafale maxi du mois'),
        ),
        migrations.AlterField(
            model_name='mensq',
            name='DXYAB',
            field=models.FloatField(default=float("nan"), null=True, verbose_name='Direction du FXYAB du mois'),
        ),
        migrations.AlterField(
            model_name='mensq',
            name='FXIAB',
            field=models.FloatField(default=float("nan"), null=True, verbose_name='Rafale maxi du mois'),
        ),
        migrations.AlterField(
            model_name='mensq',
            name='FXIDAT',
            field=models.DateTimeField(default=float("nan"), null=True, verbose_name='Date la rafale maxi du mois'),
        ),
        migrations.AlterField(
            model_name='mensq',
            name='FXYAB',
            field=models.FloatField(default=float("nan"), null=True, verbose_name='FXY max du mois'),
        ),
        migrations.AlterField(
            model_name='mensq',
            name='FXYABDAT',
            field=models.DateTimeField(default=float("nan"), null=True, verbose_name='Date du FXYAB du moise'),
        ),
        migrations.AlterField(
            model_name='mensq',
            name='HFM',
            field=models.FloatField(default=float("nan"), null=True),
        ),
        migrations.AlterField(
            model_name='mensq',
            name='HFN',
            field=models.FloatField(default=float("nan"), null=True),
        ),
        migrations.AlterField(
            model_name='mensq',
            name='HFX',
            field=models.FloatField(default=float("nan"), null=True),
        ),
        migrations.AlterField(
            model_name='mensq',
            name='HSM',
            field=models.FloatField(default=float("nan"), null=True),
        ),
        migrations.AlterField(
            model_name='mensq',
            name='HSN',
            field=models.FloatField(default=float("nan"), null=True),
        ),
        migrations.AlterField(
            model_name='mensq',
            name='HSX',
            field=models.FloatField(default=float("nan"), null=True),
        ),
        migrations.AlterField(
            model_name='mensq',
            name='INST',
            field=models.IntegerField(default=float("nan"), null=True, verbose_name="Duree d'insolation quotidienne moyenne (min,default=math.nan)"),
        ),
        migrations.AlterField(
            model_name='mensq',
            name='NBJFF10',
            field=models.IntegerField(default=float("nan"), null=True, verbose_name='Nombre de jours ou FF est sup à 10m/s'),
        ),
        migrations.AlterField(
            model_name='mensq',
            name='NBJFF16',
            field=models.IntegerField(default=float("nan"), null=True, verbose_name='Nombre de jours ou FF est sup à 16m/s'),
        ),
        migrations.AlterField(
            model_name='mensq',
            name='NBJFF28',
            field=models.IntegerField(default=float("nan"), null=True, verbose_name='Nombre de jours ou FF est sup à 28m/s'),
        ),
        migrations.AlterField(
            model_name='mensq',
            name='NBJFXY10',
            field=models.IntegerField(default=float("nan"), null=True, verbose_name='Nombre de jours ou FXY est sup à 10m/s'),
        ),
        migrations.AlterField(
            model_name='mensq',
            name='NBJFXY15',
            field=models.IntegerField(default=float("nan"), null=True, verbose_name='Nombre de jours ou FXY est sup à 15m/s'),
        ),
        migrations.AlterField(
            model_name='mensq',
            name='NBJFXY8',
            field=models.IntegerField(default=float("nan"), null=True, verbose_name='Nombre de jours ou FXY est sup à 8m/s'),
        ),
        migrations.AlterField(
            model_name='mensq',
            name='NBJGELEE',
            field=models.IntegerField(default=float("nan"), null=True, verbose_name='Nombre de jours ou la TN est inf à 0'),
        ),
        migrations.AlterField(
            model_name='mensq',
            name='NBJRR1',
            field=models.IntegerField(default=float("nan"), null=True, verbose_name='Nb de jours RR sup à 1mm'),
        ),
        migrations.AlterField(
            model_name='mensq',
            name='NBJRR10',
            field=models.IntegerField(default=float("nan"), null=True, verbose_name='Nb de jours RR sup à 10mm'),
        ),
        migrations.AlterField(
            model_name='mensq',
            name='NBJRR100',
            field=models.IntegerField(default=float("nan"), null=True, verbose_name='Nb de jours RR sup à 100mm'),
        ),
        migrations.AlterField(
            model_name='mensq',
            name='NBJRR30',
            field=models.IntegerField(default=float("nan"), null=True, verbose_name='Nb de jours RR sup à 30mm'),
        ),
        migrations.AlterField(
            model_name='mensq',
            name='NBJRR5',
            field=models.IntegerField(default=float("nan"), null=True, verbose_name='Nb de jours RR sup à 5mm'),
        ),
        migrations.AlterField(
            model_name='mensq',
            name='NBJRR50',
            field=models.IntegerField(default=float("nan"), null=True, verbose_name='Nb de jours RR sup à 50mm'),
        ),
        migrations.AlterField(
            model_name='mensq',
            name='NBJTN5',
            field=models.IntegerField(default=float("nan"), null=True, verbose_name='Nombre de jours ou la TN est inf à -5'),
        ),
        migrations.AlterField(
            model_name='mensq',
            name='NBJTNI10',
            field=models.IntegerField(default=float("nan"), null=True, verbose_name='Nombre de jours ou la TN est inf à 10'),
        ),
        migrations.AlterField(
            model_name='mensq',
            name='NBJTNI15',
            field=models.IntegerField(default=float("nan"), null=True, verbose_name='Nombre de jours ou la TN est inf à 15'),
        ),
        migrations.AlterField(
            model_name='mensq',
            name='NBJTNI20',
            field=models.IntegerField(default=float("nan"), null=True, verbose_name='Nombre de jours ou la TN est inf à 20'),
        ),
        migrations.AlterField(
            model_name='mensq',
            name='NBJTNS20',
            field=models.IntegerField(default=float("nan"), null=True, verbose_name='Nombre de jours ou la TN est sup à 20'),
        ),
        migrations.AlterField(
            model_name='mensq',
            name='NBJTNS25',
            field=models.IntegerField(default=float("nan"), null=True, verbose_name='Nombre de jours ou la TN est sup à 25'),
        ),
        migrations.AlterField(
            model_name='mensq',
            name='NBJTX0',
            field=models.IntegerField(default=float("nan"), null=True, verbose_name='Nombre de jours ou la TX est inf à 0'),
        ),
        migrations.AlterField(
            model_name='mensq',
            name='NBJTX25',
            field=models.IntegerField(default=float("nan"), null=True, verbose_name='Nombre de jours ou la TX est sup à 25'),
        ),
        migrations.AlterField(
            model_name='mensq',
            name='NBJTX30',
            field=models.IntegerField(default=float("nan"), null=True, verbose_name='Nombre de jours ou la TX est sup à 30'),
        ),
        migrations.AlterField(
            model_name='mensq',
            name='NBJTX32',
            field=models.IntegerField(default=float("nan"), null=True, verbose_name='Nombre de jours ou la TX est sup à 32'),
        ),
        migrations.AlterField(
            model_name='mensq',
            name='NBJTX35',
            field=models.IntegerField(default=float("nan"), null=True, verbose_name='Nombre de jours ou la TX est sup à 35'),
        ),
        migrations.AlterField(
            model_name='mensq',
            name='NBJTXI20',
            field=models.IntegerField(default=float("nan"), null=True, verbose_name='Nombre de jours ou la TX est inf à 20'),
        ),
        migrations.AlterField(
            model_name='mensq',
            name='NBJTXI27',
            field=models.IntegerField(default=float("nan"), null=True, verbose_name='Nombre de jours ou la TX est inf à 27'),
        ),
        migrations.AlterField(
            model_name='mensq',
            name='PMERM',
            field=models.FloatField(default=float("nan"), null=True),
        ),
        migrations.AlterField(
            model_name='mensq',
            name='PMERMINAB',
            field=models.FloatField(default=float("nan"), null=True),
        ),
        migrations.AlterField(
            model_name='mensq',
            name='PMERMINABDAT',
            field=models.DateTimeField(default=float("nan"), null=True),
        ),
        migrations.AlterField(
            model_name='mensq',
            name='RR',
            field=models.FloatField(default=float("nan"), null=True),
        ),
        migrations.AlterField(
            model_name='mensq',
            name='RRAB',
            field=models.FloatField(default=float("nan"), null=True, verbose_name='Precipitation maxi en 24h'),
        ),
        migrations.AlterField(
            model_name='mensq',
            name='RRABDAT',
            field=models.DateTimeField(default=float("nan"), null=True),
        ),
        migrations.AlterField(
            model_name='mensq',
            name='STATUS_DRR',
            field=models.IntegerField(default=float("nan"), null=True, verbose_name='1 - Relevé manuel, 2 - Relevé automatique'),
        ),
        migrations.AlterField(
            model_name='mensq',
            name='STATUS_RRAB',
            field=models.IntegerField(default=float("nan"), null=True, verbose_name='1 - Relevé manuel, 2 - Relevé automatique'),
        ),
        migrations.AlterField(
            model_name='mensq',
            name='TN',
            field=models.FloatField(default=float("nan"), null=True, verbose_name='Moyenne des TN du mois'),
        ),
        migrations.AlterField(
            model_name='mensq',
            name='TNAB',
            field=models.FloatField(default=float("nan"), null=True, verbose_name='TN min du mois'),
        ),
        migrations.AlterField(
            model_name='mensq',
            name='TNDAT',
            field=models.DateTimeField(default=float("nan"), null=True, verbose_name='Date de la TN min du mois'),
        ),
        migrations.AlterField(
            model_name='mensq',
            name='TNMAX',
            field=models.FloatField(default=float("nan"), null=True, verbose_name='TN max du mois'),
        ),
        migrations.AlterField(
            model_name='mensq',
            name='TNMAXDAT',
            field=models.DateTimeField(default=float("nan"), null=True, verbose_name='Date de la TN max du mois'),
        ),
        migrations.AlterField(
            model_name='mensq',
            name='TSM',
            field=models.FloatField(default=float("nan"), null=True),
        ),
        migrations.AlterField(
            model_name='mensq',
            name='TSN',
            field=models.FloatField(default=float("nan"), null=True),
        ),
        migrations.AlterField(
            model_name='mensq',
            name='TSX',
            field=models.FloatField(default=float("nan"), null=True),
        ),
        migrations.AlterField(
            model_name='mensq',
            name='TX',
            field=models.FloatField(default=float("nan"), null=True, verbose_name='Moyenne des TX du mois'),
        ),
        migrations.AlterField(
            model_name='mensq',
            name='TXAB',
            field=models.FloatField(default=float("nan"), null=True, verbose_name='TX max du mois'),
        ),
        migrations.AlterField(
            model_name='mensq',
            name='TXABDAT',
            field=models.DateTimeField(default=float("nan"), null=True, verbose_name='Date de la TX max du mois'),
        ),
        migrations.AlterField(
            model_name='mensq',
            name='TXMIN',
            field=models.FloatField(default=float("nan"), null=True, verbose_name='TX min du mois'),
        ),
        migrations.AlterField(
            model_name='mensq',
            name='TXMINDAT',
            field=models.DateTimeField(default=float("nan"), null=True, verbose_name='Date de la TX min du mois'),
        ),
        migrations.AlterField(
            model_name='mensq',
            name='UMM',
            field=models.FloatField(default=float("nan"), null=True, verbose_name='Moyenne des humidites relatives du mois'),
        ),
        migrations.AlterField(
            model_name='mensq',
            name='UNAB',
            field=models.FloatField(default=float("nan"), null=True, verbose_name='Humidite relative minimale du mois'),
        ),
        migrations.AlterField(
            model_name='mensq',
            name='UNABDAT',
            field=models.DateTimeField(default=float("nan"), null=True, verbose_name="Date de l'Humidite relative minimale du mois"),
        ),
        migrations.AlterField(
            model_name='mensq',
            name='UXAB',
            field=models.FloatField(default=float("nan"), null=True, verbose_name='Humidite relative maximale du mois'),
        ),
        migrations.AlterField(
            model_name='mensq',
            name='UXABDAT',
            field=models.DateTimeField(default=float("nan"), null=True, verbose_name="Date de l'humidite relative maximale du mois"),
        ),
        migrations.AlterField(
            model_name='pays',
            name='CODPAYS',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='poste',
            name='CP',
            field=models.IntegerField(default=float("nan"), verbose_name='Code postal'),
        ),
        migrations.AlterField(
            model_name='q',
            name='DG',
            field=models.IntegerField(default=float("nan"), null=True, verbose_name='Duree du gel en min'),
        ),
        migrations.AlterField(
            model_name='q',
            name='DRR',
            field=models.FloatField(default=float("nan"), null=True, verbose_name='Durée de la précipitation en min'),
        ),
        migrations.AlterField(
            model_name='q',
            name='DXI',
            field=models.FloatField(default=float("nan"), null=True, verbose_name='Direction de FXI'),
        ),
        migrations.AlterField(
            model_name='q',
            name='DXY',
            field=models.FloatField(default=float("nan"), null=True, verbose_name='Direction de FXY'),
        ),
        migrations.AlterField(
            model_name='q',
            name='ETPM',
            field=models.FloatField(default=float("nan"), null=True),
        ),
        migrations.AlterField(
            model_name='q',
            name='FXI',
            field=models.FloatField(default=float("nan"), null=True, verbose_name='Rafales max de FF dans la journee'),
        ),
        migrations.AlterField(
            model_name='q',
            name='FXY',
            field=models.FloatField(default=float("nan"), null=True, verbose_name='Valeur max de FF dans la journee'),
        ),
        migrations.AlterField(
            model_name='q',
            name='HFM',
            field=models.FloatField(default=float("nan"), null=True),
        ),
        migrations.AlterField(
            model_name='q',
            name='HFMN',
            field=models.FloatField(default=float("nan"), null=True),
        ),
        migrations.AlterField(
            model_name='q',
            name='HFMX',
            field=models.FloatField(default=float("nan"), null=True),
        ),
        migrations.AlterField(
            model_name='q',
            name='HSM',
            field=models.FloatField(default=float("nan"), null=True),
        ),
        migrations.AlterField(
            model_name='q',
            name='HSMN',
            field=models.FloatField(default=float("nan"), null=True),
        ),
        migrations.AlterField(
            model_name='q',
            name='HSMX',
            field=models.FloatField(default=float("nan"), null=True),
        ),
        migrations.AlterField(
            model_name='q',
            name='HTN',
            field=models.DateTimeField(default=float("nan"), null=True, verbose_name='AAAA MM JJ HH MM de TN'),
        ),
        migrations.AlterField(
            model_name='q',
            name='HTX',
            field=models.DateTimeField(default=float("nan"), null=True, verbose_name='AAAA MM JJ HH MM de TX'),
        ),
        migrations.AlterField(
            model_name='q',
            name='HUN',
            field=models.DateTimeField(default=float("nan"), null=True, verbose_name='AAAA MM JJ HH MM de UN'),
        ),
        migrations.AlterField(
            model_name='q',
            name='HUX',
            field=models.DateTimeField(default=float("nan"), null=True, verbose_name='AAAA MM JJ HH MM de UX'),
        ),
        migrations.AlterField(
            model_name='q',
            name='HXI',
            field=models.DateTimeField(default=float("nan"), null=True, verbose_name='AAAA MM JJ HH MM de FXI'),
        ),
        migrations.AlterField(
            model_name='q',
            name='HXY',
            field=models.DateTimeField(default=float("nan"), null=True, verbose_name='AAAA MM JJ HH MM de FXY'),
        ),
        migrations.AlterField(
            model_name='q',
            name='INST',
            field=models.IntegerField(default=float("nan"), null=True, verbose_name="Duree d'insolation quotidienne (min)"),
        ),
        migrations.AlterField(
            model_name='q',
            name='PMERM',
            field=models.FloatField(default=float("nan"), null=True),
        ),
        migrations.AlterField(
            model_name='q',
            name='PMERMIN',
            field=models.FloatField(default=float("nan"), null=True),
        ),
        migrations.AlterField(
            model_name='q',
            name='RR',
            field=models.FloatField(default=float("nan"), null=True),
        ),
        migrations.AlterField(
            model_name='q',
            name='STATUS_DRR',
            field=models.IntegerField(default=float("nan"), null=True, verbose_name='1 - Relevé manuel, 2 - Relevé automatique'),
        ),
        migrations.AlterField(
            model_name='q',
            name='TM',
            field=models.FloatField(default=float("nan"), null=True),
        ),
        migrations.AlterField(
            model_name='q',
            name='TN',
            field=models.FloatField(default=float("nan"), null=True),
        ),
        migrations.AlterField(
            model_name='q',
            name='TS',
            field=models.FloatField(default=float("nan"), null=True),
        ),
        migrations.AlterField(
            model_name='q',
            name='TSN',
            field=models.FloatField(default=float("nan"), null=True),
        ),
        migrations.AlterField(
            model_name='q',
            name='TSX',
            field=models.FloatField(default=float("nan"), null=True),
        ),
        migrations.AlterField(
            model_name='q',
            name='TX',
            field=models.FloatField(default=float("nan"), null=True),
        ),
        migrations.AlterField(
            model_name='q',
            name='UM',
            field=models.FloatField(default=float("nan"), null=True),
        ),
        migrations.AlterField(
            model_name='q',
            name='UN',
            field=models.FloatField(default=float("nan"), null=True, verbose_name='Humidite minimale dans la journee'),
        ),
        migrations.AlterField(
            model_name='q',
            name='UX',
            field=models.FloatField(default=float("nan"), null=True, verbose_name="Humidite maximale dans l'heure"),
        ),
    ]
