# Generated by Django 2.0.6 on 2018-07-25 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0024_auto_20180723_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='h',
            name='INST',
            field=models.FloatField(default=None, null=True),
        ),
    ]
