# Generated by Django 2.0.6 on 2018-07-31 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0025_h_inst'),
    ]

    operations = [
        migrations.AlterField(
            model_name='h',
            name='FF',
            field=models.FloatField(default=None, null=True, verbose_name='Force du vent moyenné sur 10 dernieres min'),
        ),
        migrations.AlterField(
            model_name='instan',
            name='DD',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='instan',
            name='DXI',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='instan',
            name='ETP',
            field=models.FloatField(default=None, null=True, verbose_name='Evapotranspiration'),
        ),
        migrations.AlterField(
            model_name='instan',
            name='FF',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='instan',
            name='FXI',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='instan',
            name='HF',
            field=models.FloatField(default=None, null=True, verbose_name='Humidite du feuillage'),
        ),
        migrations.AlterField(
            model_name='instan',
            name='HS',
            field=models.FloatField(default=None, null=True, verbose_name='Humidite du sol'),
        ),
        migrations.AlterField(
            model_name='instan',
            name='IC',
            field=models.FloatField(default=None, null=True, verbose_name='Indice de chaleur'),
        ),
        migrations.AlterField(
            model_name='instan',
            name='PMER',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='instan',
            name='RAD',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='instan',
            name='RR',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='instan',
            name='RRI',
            field=models.FloatField(default=None, null=True, verbose_name='Intensité max des precipitations'),
        ),
        migrations.AlterField(
            model_name='instan',
            name='T',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='instan',
            name='TD',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='instan',
            name='TS',
            field=models.FloatField(default=None, null=True, verbose_name='Temperature du sol'),
        ),
        migrations.AlterField(
            model_name='instan',
            name='U',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='instan',
            name='UV',
            field=models.FloatField(default=None, null=True, verbose_name='Indice UV'),
        ),
        migrations.AlterField(
            model_name='instan',
            name='WINDCHILL',
            field=models.FloatField(default=None, null=True),
        ),
    ]
