# Generated by Django 2.0.6 on 2018-08-20 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0026_auto_20180731_1031'),
    ]

    operations = [
        migrations.CreateModel(
            name='EVENEMENTS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DEBUT', models.DateTimeField(null=True)),
                ('FIN', models.DateTimeField(null=True)),
                ('EVENEMENT', models.CharField(max_length=25, null=True)),
                ('POSTE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.POSTE')),
            ],
        ),
        migrations.AlterField(
            model_name='instan',
            name='DD',
            field=models.FloatField(default=float("nan"), null=True),
        ),
        migrations.AlterField(
            model_name='instan',
            name='DXI',
            field=models.FloatField(default=float("nan"), null=True),
        ),
        migrations.AlterField(
            model_name='instan',
            name='ETP',
            field=models.FloatField(default=float("nan"), null=True, verbose_name='Evapotranspiration'),
        ),
        migrations.AlterField(
            model_name='instan',
            name='FF',
            field=models.FloatField(default=float("nan"), null=True),
        ),
        migrations.AlterField(
            model_name='instan',
            name='FXI',
            field=models.FloatField(default=float("nan"), null=True),
        ),
        migrations.AlterField(
            model_name='instan',
            name='HF',
            field=models.FloatField(default=float("nan"), null=True, verbose_name='Humidite du feuillage'),
        ),
        migrations.AlterField(
            model_name='instan',
            name='HS',
            field=models.FloatField(default=float("nan"), null=True, verbose_name='Humidite du sol'),
        ),
        migrations.AlterField(
            model_name='instan',
            name='IC',
            field=models.FloatField(default=float("nan"), null=True, verbose_name='Indice de chaleur'),
        ),
        migrations.AlterField(
            model_name='instan',
            name='PMER',
            field=models.FloatField(default=float("nan"), null=True),
        ),
        migrations.AlterField(
            model_name='instan',
            name='RAD',
            field=models.FloatField(default=float("nan"), null=True),
        ),
        migrations.AlterField(
            model_name='instan',
            name='RR',
            field=models.FloatField(default=float("nan"), null=True),
        ),
        migrations.AlterField(
            model_name='instan',
            name='RRI',
            field=models.FloatField(default=float("nan"), null=True, verbose_name='Intensité max des precipitations'),
        ),
        migrations.AlterField(
            model_name='instan',
            name='T',
            field=models.FloatField(default=float("nan"), null=True),
        ),
        migrations.AlterField(
            model_name='instan',
            name='TD',
            field=models.FloatField(default=float("nan"), null=True),
        ),
        migrations.AlterField(
            model_name='instan',
            name='TS',
            field=models.FloatField(default=float("nan"), null=True, verbose_name='Temperature du sol'),
        ),
        migrations.AlterField(
            model_name='instan',
            name='U',
            field=models.FloatField(default=float("nan"), null=True),
        ),
        migrations.AlterField(
            model_name='instan',
            name='UV',
            field=models.FloatField(default=float("nan"), null=True, verbose_name='Indice UV'),
        ),
        migrations.AlterField(
            model_name='instan',
            name='WINDCHILL',
            field=models.FloatField(default=float("nan"), null=True),
        ),
        migrations.AlterField(
            model_name='mensq',
            name='NBJFF10',
            field=models.IntegerField(default=None, null=True, verbose_name='Nombre de jours ou FXI est sup à 10m/s'),
        ),
        migrations.AlterField(
            model_name='mensq',
            name='NBJFF16',
            field=models.IntegerField(default=None, null=True, verbose_name='Nombre de jours ou FXI est sup à 16m/s'),
        ),
        migrations.AlterField(
            model_name='mensq',
            name='NBJFF28',
            field=models.IntegerField(default=None, null=True, verbose_name='Nombre de jours ou FXI est sup à 28m/s'),
        ),
    ]
