# Generated by Django 2.0.6 on 2018-08-20 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0027_auto_20180820_0857'),
    ]

    operations = [
        migrations.CreateModel(
            name='POSTE_EVENEMENTS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='evenements',
            name='EVENEMENT',
        ),
        migrations.RemoveField(
            model_name='evenements',
            name='POSTE',
        ),
        migrations.AddField(
            model_name='evenements',
            name='NOM_EVENEMENT',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='instan',
            name='DD',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='instan',
            name='DXI',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='instan',
            name='ETP',
            field=models.FloatField(default=None, null=True, verbose_name='Evapotranspiration'),
        ),
        migrations.AlterField(
            model_name='instan',
            name='FF',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='instan',
            name='FXI',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='instan',
            name='HF',
            field=models.FloatField(default=None, null=True, verbose_name='Humidite du feuillage'),
        ),
        migrations.AlterField(
            model_name='instan',
            name='HS',
            field=models.FloatField(default=None, null=True, verbose_name='Humidite du sol'),
        ),
        migrations.AlterField(
            model_name='instan',
            name='IC',
            field=models.FloatField(default=None, null=True, verbose_name='Indice de chaleur'),
        ),
        migrations.AlterField(
            model_name='instan',
            name='PMER',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='instan',
            name='RAD',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='instan',
            name='RR',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='instan',
            name='RRI',
            field=models.FloatField(default=None, null=True, verbose_name='Intensité max des precipitations'),
        ),
        migrations.AlterField(
            model_name='instan',
            name='T',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='instan',
            name='TD',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='instan',
            name='TS',
            field=models.FloatField(default=None, null=True, verbose_name='Temperature du sol'),
        ),
        migrations.AlterField(
            model_name='instan',
            name='U',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='instan',
            name='UV',
            field=models.FloatField(default=None, null=True, verbose_name='Indice UV'),
        ),
        migrations.AlterField(
            model_name='instan',
            name='WINDCHILL',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='poste_evenements',
            name='EVENEMENTS',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.EVENEMENTS'),
        ),
        migrations.AddField(
            model_name='poste_evenements',
            name='POSTE',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.POSTE'),
        ),
    ]
