# Generated by Django 2.1 on 2018-08-30 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0030_auto_20180829_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='poste',
            name='INIT',
            field=models.IntegerField(default=None, null=True, verbose_name="Etat d'initialisation"),
        ),
    ]
