# Generated by Django 2.1 on 2018-08-30 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0031_poste_init'),
    ]

    operations = [
        migrations.AddField(
            model_name='poste',
            name='PASDETEMPS',
            field=models.IntegerField(default=5, verbose_name="Pas de temps d'envoie (min)"),
        ),
    ]
