# Generated by Django 2.1 on 2018-09-05 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0032_poste_pdt'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenements',
            name='TYPE_EVENEMENT',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
