# Generated by Django 2.1.4 on 2018-12-10 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0033_evenements_type_evenement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='POSTE',
        ),
        migrations.AddField(
            model_name='commune',
            name='CP',
            field=models.IntegerField(default=0000, verbose_name='Code postal'),
        ),
        migrations.DeleteModel(
            name='Files',
        ),
    ]
