version: "3.4"
services:




  tempo:
    image: grafana/tempo:0.7.0
    command: ["-config.file=/etc/tempo.yaml"]
    ports:
    - "3100:3100"
    - "55680:55680"
    volumes:
      - ./config/tempo.yaml:/etc/tempo.yaml
      - ./example-data/tempo:/tmp/tempo
    logging:
      driver: loki
      options:
        loki-url: 'http://localhost:3110/api/prom/push'

  otel-collector:
    image: otel/opentelemetry-collector:0.25.0
    ports:
    - "6831:6831"
    - "14268:14268"
    - "4317:4317"
    volumes:
    - ./config/otel-collector.yaml:/config/otel-collector.yaml
    command:
    - --config=/config/otel-collector.yaml
      
  tempo-query:
    image: grafana/tempo-query:0.7.0
    environment:
    - BACKEND=tempo:80
    volumes:
    - ./etc/tempo-query.yaml:/etc/tempo-query.yaml
    ports:
    - "16686:16686"  # jaeger-ui
    depends_on:
    - tempo
    logging:
      driver: loki
      options:
        loki-url: 'http://localhost:3100/api/prom/push'

  grafana:
    image: grafana/grafana:7.3.x-exemplars
    volumes:
    - ./config/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
    environment:
    - GF_AUTH_ANONYMOUS_ENABLED=true
    - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    - GF_AUTH_DISABLE_LOGIN_FORM=true
    ports:
    - "3000:3000"

  loki:
    image: grafana/loki:2.2.1
    command: -config.file=/etc/loki/local-config.yaml
    ports:
    - "3110:3100"
    logging:
      driver: loki
      options:
        loki-url: 'http://localhost:3100/api/prom/push'

  prometheus:
    image: cstyan/prometheus:exemplars-64206a
    volumes:
      - ./config/prometheus.yaml:/etc/prometheus.yaml
    entrypoint:
      - /bin/prometheus
      - --config.file=/etc/prometheus.yaml
    ports:
      - "9090:9090"