{
 "title": "Admin",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Exceptions sur la période",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timescaledb_experimental.time_bucket_ng('1 day', dat::timestamptz) as time,\n  count(*)\nFROM incidents\nWHERE\n  $__timeFilter(dat::timestamp)\n  and active = true\n  and source = 'exception'\ngroup by 1"
    }
   ]
  },
  {
   "title": "Active Incidents",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 3, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  timescaledb_experimental.time_bucket_ng('1 day', dat::timestamptz) as time,\n  count(*) as critical\nFROM incidents\nWHERE\n  $__timeFilter(dat)\n  and active = true\n  and level = 'critical'\ngroup by 1"
    },
    {
     "rawSql": "SELECT\n  timescaledb_experimental.time_bucket_ng('1 day', dat::timestamptz) as time,\n  count(*) as error\nFROM incidents\nWHERE\n  $__timeFilter(dat)\n  and active = true\n  and level = 'error'\ngroup by 1"
    },
    {
     "rawSql": "SELECT\n  timescaledb_experimental.time_bucket_ng('1 day', dat::timestamptz) as time,\n  count(*) AS \"info\"\nFROM incidents\nWHERE\n  $__timeFilter(dat)\n  and active = true\n  and level = 'info'\ngroup by 1"
    }
   ]
  },
  {
   "title": "status synchronisation",
   "type": "table",
   "gridPos": { "h": 25, "w": 7, "x": 17, "y": 0 },
   "targets": [
    {
     "rawSql": "select\n  p.meteor as meteor,\n  p.last_obs_date_local,\n  p.last_extremes_date\n  from postes p\n  where p.last_obs_date_local is not null or p.last_extremes_date is not null\n  order by 2 desc\n"
    }
   ]
  },
  {
   "title": "django log",
   "type": "logs",
   "gridPos": { "h": 18, "w": 16, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "{job=\"django\"} | logfmt"
    }
   ]
  }
 ]
}