{
 "title": "newClim2",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "agg_todo in Error",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*) as on_error FROM agg_todo where status = 9"
    }
   ]
  },
  {
   "title": "Aggreg on processing",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*) as on_processing FROM agg_todo where status = 1"
    }
   ]
  },
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Calc Queue length",
   "type": "barchart",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 6 },
   "targets": [
    {
     "rawSql": "select poste.meteor, count(agg_todo.*) as queue from agg_todo join obs on agg_todo.obs_id_id = obs.id join poste on obs.poste_id_id = poste.id group by 1;\n"
    }
   ]
  },
  { "title": "Log Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Log Rate per Level",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 21, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "avg(rate({job=\"django_debug\"} |json level=\"level\" [1m])) by (level)",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "Json Load Rate",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count_over_time({job=\"django_debug\"} |= \"Json file loaded\" | json meteor=\"params.meteor\" [5s])",
     "legendFormat": "{{meteor}}"
    }
   ]
  },
  {
   "title": "Json Load Perf",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 9, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg_over_time({job=\"django_debug\"} |= \"Json file loaded\" | json exec=\"params.timeExec\", meteor=\"params.meteor\" | unwrap exec | __error__ = \"\"  [1h]) by (meteor)",
     "legendFormat": "{{meteor}}"
    }
   ]
  },
  { "title": "Json Processing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Calc Rate",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count_over_time({job=\"django_debug\"} |= \"Aggregation\" | json meteor=\"params.meteor\" | __error__ = \"\"  [5s])",
     "legendFormat": "{{meteor}}"
    }
   ]
  },
  {
   "title": "Calc Perf",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 9, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg_over_time({job=\"django_debug\"} |= \"Aggregation computed\" | json exec=\"params.timeExec\", meteor=\"params.meteor\" | unwrap exec | __error__ = \"\"  [5s]) by (meteor)",
     "legendFormat": "{{meteor}}"
    }
   ]
  },
  {
   "title": "Log Detail",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "All Logs",
     "type": "logs",
     "gridPos": { "h": 4, "w": 21, "x": 0, "y": 23 },
     "targets": [
      {
       "expr": "{job=\"django_debug\"}"
      }
     ]
    },
    {
     "title": "Critical Logs",
     "type": "graph",
     "gridPos": { "h": 5, "w": 21, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "{job=\"django_debug\"} |= \"critical\""
      }
     ]
    }
   ]
  }
 ]
}