# Generated by Django 3.1.5 on 2021-02-09 08:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meteor', models.CharField(max_length=10, verbose_name='Code MeteoR.OI')),
                ('meteofr', models.CharField(max_length=10, null=True, verbose_name='Code Meteo France')),
                ('title', models.CharField(max_length=50, verbose_name='Nom clair de la station')),
                ('cas_gestion_extreme', models.CharField(choices=[('0', 'Unconnu'), ('1', 'Auto dans observation'), ('2', 'Auto dans agrégation'), ('3', 'Manuel')], default='0', max_length=1, verbose_name='Gestion des extrêmes')),
                ('agg_min_extreme', models.CharField(choices=[('', 'not set'), ('H', 'Heure'), ('D', 'Day'), ('M', 'Month'), ('Y', 'Year'), ('A', 'Global')], default='', max_length=1, null=True, verbose_name='Niveau Agregation, Auto dans agregation')),
                ('owner', models.CharField(max_length=50, verbose_name='Station Owner Name')),
                ('email', models.CharField(max_length=50, verbose_name='E-Mail')),
                ('phone', models.CharField(max_length=50, verbose_name='Phone')),
                ('address', models.CharField(max_length=50, verbose_name='Address')),
                ('zip', models.CharField(default='', max_length=10, verbose_name='Zip')),
                ('city', models.CharField(default='', max_length=50, verbose_name='City')),
                ('country', models.CharField(default='', max_length=50, verbose_name='Country')),
                ('latitude', models.FloatField(default=0, verbose_name='Latitude')),
                ('longitude', models.FloatField(default=0, verbose_name='Longitude')),
                ('start', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date d'entrée dans le réseau")),
                ('end', models.DateTimeField(null=True, verbose_name='Date de sortie du réseau')),
                ('comment', models.TextField(default=None, null=True)),
            ],
            options={
                'db_table': 'poste',
            },
        ),
        migrations.CreateModel(
            name='Agg_year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dat', models.DateTimeField()),
                ('last_rec_dat', models.DateTimeField(default=django.utils.timezone.now)),
                ('duration', models.IntegerField()),
                ('qa_modifications', models.IntegerField(default='0')),
                ('qa_incidents', models.IntegerField(default='0')),
                ('qa_check_done', models.BooleanField(default=False)),
                ('j', models.JSONField(verbose_name='JsonB')),
                ('poste_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.poste')),
            ],
            options={
                'db_table': 'agg_year',
            },
        ),
        migrations.CreateModel(
            name='Agg_month',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dat', models.DateTimeField()),
                ('last_rec_dat', models.DateTimeField(default=django.utils.timezone.now)),
                ('duration', models.IntegerField()),
                ('qa_modifications', models.IntegerField(default='0')),
                ('qa_incidents', models.IntegerField(default='0')),
                ('qa_check_done', models.BooleanField(default=False)),
                ('j', models.JSONField(verbose_name='JsonB')),
                ('poste_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.poste')),
            ],
            options={
                'db_table': 'agg_month',
            },
        ),
        migrations.CreateModel(
            name='Agg_hour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dat', models.DateTimeField()),
                ('last_rec_dat', models.DateTimeField(default=django.utils.timezone.now)),
                ('duration', models.IntegerField()),
                ('qa_modifications', models.IntegerField(default='0')),
                ('qa_incidents', models.IntegerField(default='0')),
                ('qa_check_done', models.BooleanField(default=False)),
                ('j', models.JSONField(verbose_name='JsonB')),
                ('poste_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.poste')),
            ],
            options={
                'db_table': 'agg_hour',
            },
        ),
        migrations.CreateModel(
            name='Agg_global',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dat', models.DateTimeField()),
                ('last_rec_dat', models.DateTimeField(default=django.utils.timezone.now)),
                ('duration', models.IntegerField()),
                ('qa_modifications', models.IntegerField(default='0')),
                ('qa_incidents', models.IntegerField(default='0')),
                ('qa_check_done', models.BooleanField(default=False)),
                ('j', models.JSONField(verbose_name='JsonB')),
                ('poste_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.poste')),
            ],
            options={
                'db_table': 'agg_global',
            },
        ),
        migrations.CreateModel(
            name='Agg_day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dat', models.DateTimeField()),
                ('last_rec_dat', models.DateTimeField(default=django.utils.timezone.now)),
                ('duration', models.IntegerField()),
                ('qa_modifications', models.IntegerField(default='0')),
                ('qa_incidents', models.IntegerField(default='0')),
                ('qa_check_done', models.BooleanField(default=False)),
                ('j', models.JSONField(verbose_name='JsonB')),
                ('poste_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.poste')),
            ],
            options={
                'db_table': 'agg_day',
            },
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dat', models.DateTimeField()),
                ('last_rec_dat', models.DateTimeField(default=django.utils.timezone.now)),
                ('duration', models.IntegerField()),
                ('qa_modifications', models.IntegerField(default='0')),
                ('qa_incidents', models.IntegerField(default='0')),
                ('qa_check_done', models.BooleanField(default=False)),
                ('j', models.JSONField(verbose_name='JsonB')),
                ('poste_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.poste')),
            ],
            options={
                'db_table': 'obs',
                'unique_together': {('poste_id', 'dat')},
            },
        ),
    ]
