# Generated by Django 3.1.5 on 2021-02-09 09:04

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Type de Donnees')),
                ('model_value', models.JSONField(verbose_name='JsonB')),
            ],
            options={
                'db_table': 'type_data',
            },
        ),
        migrations.CreateModel(
            name='Exclusion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_x', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_x', models.DateTimeField(default=datetime.datetime(2100, 12, 21, 0, 0))),
                ('value', models.JSONField(verbose_name='JsonB')),
                ('poste_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.poste')),
                ('type_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.typedata')),
            ],
            options={
                'db_table': 'exclusion',
            },
        ),
    ]
