# Generated by Django 3.2.9 on 2021-12-09 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='stop_dat',
            field=models.DateTimeField(max_length=20, verbose_name='stop date, date de la mesure'),
        ),
    ]
