# Generated by Django 3.1.7 on 2021-02-24 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agg_day',
            name='level',
            field=models.CharField(default='?', max_length=1),
        ),
        migrations.AddField(
            model_name='agg_global',
            name='level',
            field=models.CharField(default='?', max_length=1),
        ),
        migrations.AddField(
            model_name='agg_hour',
            name='level',
            field=models.CharField(default='?', max_length=1),
        ),
        migrations.AddField(
            model_name='agg_month',
            name='level',
            field=models.CharField(default='?', max_length=1),
        ),
        migrations.AddField(
            model_name='agg_year',
            name='level',
            field=models.CharField(default='?', max_length=1),
        ),
    ]
