# Generated by Django 5.0.2 on 2024-06-14 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poste',
            name='load_type',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Load From Dump'), (2, 'Load From Json'), (3, 'Load From Dump Then Json'), (4, 'Load Csv For Meteofr'), (8, 'Load Csv For Ovpf')], db_default=0, null=True, verbose_name='Type de chargement des donnees'),
        ),
    ]
