# Generated by Django 3.1.7 on 2021-04-07 15:51

import app.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agg_day',
            name='j',
            field=app.models.DateJSONField(max_length=64000),
        ),
        migrations.AlterField(
            model_name='agg_global',
            name='j',
            field=app.models.DateJSONField(max_length=64000),
        ),
        migrations.AlterField(
            model_name='agg_hour',
            name='j',
            field=app.models.DateJSONField(max_length=64000),
        ),
        migrations.AlterField(
            model_name='agg_month',
            name='j',
            field=app.models.DateJSONField(max_length=64000),
        ),
        migrations.AlterField(
            model_name='agg_todo',
            name='j_dv',
            field=app.models.DateJSONField(max_length=64500, verbose_name='default_values coming from obs processing'),
        ),
        migrations.AlterField(
            model_name='agg_todo',
            name='j_error',
            field=app.models.DateJSONField(max_length=64500, verbose_name='error reporting'),
        ),
        migrations.AlterField(
            model_name='agg_year',
            name='j',
            field=app.models.DateJSONField(max_length=64000),
        ),
        migrations.AlterField(
            model_name='exclusion',
            name='value',
            field=app.models.DateJSONField(max_length=64500, verbose_name='JsonB'),
        ),
        migrations.AlterField(
            model_name='extreme_todo',
            name='j_invalid',
            field=app.models.DateJSONField(max_length=64000),
        ),
        migrations.AlterField(
            model_name='observation',
            name='j',
            field=app.models.DateJSONField(max_length=64000),
        ),
        migrations.AlterField(
            model_name='observation',
            name='j_agg',
            field=app.models.DateJSONField(max_length=64000),
        ),
    ]
