# Generated by Django 5.0.2 on 2024-04-24 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poste',
            name='load_type',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Load From Dump'), (2, 'Load From Json'), (4, 'Load From Dump Then Json'), (8, 'Load From Csv File'), (16, 'Load Csv For Ovpf')], default=0, verbose_name='Type de chargement des donnees'),
        ),
    ]
