# Generated by Django 3.1.5 on 2021-02-21 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agg_day',
            name='j',
            field=models.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='agg_global',
            name='j',
            field=models.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='agg_hour',
            name='j',
            field=models.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='agg_month',
            name='j',
            field=models.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='agg_year',
            name='j',
            field=models.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='observation',
            name='j',
            field=models.JSONField(default={}),
        ),
    ]
