# Generated by Django 4.2.6 on 2024-01-28 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poste',
            name='load_dump',
        ),
        migrations.RemoveField(
            model_name='poste',
            name='load_raw_data',
        ),
        migrations.RemoveField(
            model_name='poste',
            name='pause_raw_data',
        ),
        migrations.AddField(
            model_name='poste',
            name='load_type',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Load From Dump'), (2, 'Load From Json'), (3, 'Load From Dump Then Json'), (4, 'Load From Csv File'), (8, 'Load From Meteofr Api'), (12, 'Load From Api And Csv')], default=0, verbose_name='Type de chargement des donnees'),
        ),
    ]
