# Generated by Django 4.2.6 on 2024-01-07 22:47

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_init_timescaledb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mesure',
            name='max_deca',
        ),
        migrations.RemoveField(
            model_name='mesure',
            name='min_deca',
        ),
        migrations.RemoveField(
            model_name='mesure',
            name='omm_link',
        ),
        migrations.RemoveField(
            model_name='mesure',
            name='val_deca',
        ),
        migrations.AlterField(
            model_name='poste',
            name='country',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='Pays'),
        ),
        migrations.AlterField(
            model_name='poste',
            name='last_obs_date',
            field=app.models.DateTimeFieldNoTZ(default='2000-01-01T00:00:00', null=True, verbose_name='Datetime UTC de derniere reception de donnees'),
        ),
    ]
