# Generated by Django 4.0.4 on 2022-05-29 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220501_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='poste',
            name='load_json',
            field=models.BooleanField(default=False, null=True, verbose_name='load json status'),
        ),
    ]
