# Generated by Django 4.2.6 on 2023-12-18 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_init_timescaledb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poste',
            name='meteor',
            field=models.CharField(max_length=50, verbose_name='Code station'),
        ),
    ]
