# Generated by Django 3.1.7 on 2021-03-07 09:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210224_0827'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agg_day',
            old_name='dat',
            new_name='start_dat',
        ),
        migrations.RenameField(
            model_name='agg_global',
            old_name='dat',
            new_name='start_dat',
        ),
        migrations.RenameField(
            model_name='agg_hour',
            old_name='dat',
            new_name='start_dat',
        ),
        migrations.RenameField(
            model_name='agg_month',
            old_name='dat',
            new_name='start_dat',
        ),
        migrations.RenameField(
            model_name='agg_year',
            old_name='dat',
            new_name='start_dat',
        ),
        migrations.AddField(
            model_name='observation',
            name='start_dat',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
