# Generated by Django 4.0.4 on 2022-06-13 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220501_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesure',
            name='field_dir',
            field=models.SmallIntegerField(null=True, verbose_name='id de la mesure wind dans table weewx.archive'),
        ),
    ]
