# Generated by Django 3.1.7 on 2021-04-07 15:55

import app.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210407_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeinstrument',
            name='model_value',
            field=app.models.DateJSONField(default={}, max_length=64500, verbose_name='JsonB'),
        ),
    ]
