# Generated by Django 4.2.6 on 2023-11-30 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_init_timescaledb'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='rain_omm_duration',
            field=models.SmallIntegerField(null=True, verbose_name='duration pluie OMM'),
        ),
    ]
