# Generated by Django 4.0.4 on 2022-05-29 14:09

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220501_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='poste',
            name='last_data',
            field=app.models.DateTimeFieldNoTZ(default='2000-01-01T00:00:00', null=True, verbose_name='Date de derniere reception de donnees'),
        ),
        migrations.AddField(
            model_name='poste',
            name='last_data_id',
            field=models.BigIntegerField(default=0, null=True, verbose_name='ID obs de la derniere reception de donnees'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='soil_moist2',
            field=models.FloatField(null=True, verbose_name='humidité du sol niveau 2'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='soil_moist3',
            field=models.FloatField(null=True, verbose_name='humidité du sol niveau 3'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='soil_moist4',
            field=models.FloatField(null=True, verbose_name='humidité du sol niveau 4'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='soil_temp2',
            field=models.FloatField(null=True, verbose_name='température du sol niveau 2'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='soil_temp3',
            field=models.FloatField(null=True, verbose_name='température du sol niveau 3'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='soil_temp4',
            field=models.FloatField(null=True, verbose_name='température du sol niveau 4'),
        ),
    ]
