# Generated by Django 3.1.5 on 2021-02-21 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210221_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agg_day',
            name='j',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='agg_global',
            name='j',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='agg_hour',
            name='j',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='agg_month',
            name='j',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='agg_year',
            name='j',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='observation',
            name='j',
            field=models.JSONField(default=dict),
        ),
    ]
