# Generated by Django 4.0.4 on 2022-05-03 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220501_2032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extreme',
            old_name='is_obs',
            new_name='id_obs',
        ),
        migrations.AddIndex(
            model_name='extreme',
            index=models.Index(condition=models.Q(('id_obs__gt', 0)), fields=['id_obs'], name='extremes_id_obs'),
        ),
    ]
