# Generated by Django 4.1.7 on 2023-05-04 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_init_timescaledb'),
    ]

    operations = [
        migrations.AddField(
            model_name='poste',
            name='pause',
            field=models.BooleanField(default=False, null=True, verbose_name='Do not process Json file'),
        ),
    ]
