# Generated by Django 3.2.9 on 2021-11-03 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_poste_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poste',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
