# Generated by Django 3.1.5 on 2021-02-09 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_exclusion_typedata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observation',
            name='j',
        ),
        migrations.AddField(
            model_name='observation',
            name='barometer',
            field=models.DecimalField(decimal_places=1, max_digits=5, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='observation',
            name='barometer_max',
            field=models.DecimalField(decimal_places=1, max_digits=5, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='observation',
            name='barometer_max_time',
            field=models.DateTimeField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='observation',
            name='barometer_min',
            field=models.DecimalField(decimal_places=1, max_digits=5, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='observation',
            name='barometer_min_time',
            field=models.DateTimeField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='observation',
            name='dewpoint',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='observation',
            name='etp',
            field=models.DecimalField(decimal_places=3, max_digits=5, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='observation',
            name='heat_index',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='observation',
            name='humidity',
            field=models.SmallIntegerField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='observation',
            name='humidity_max',
            field=models.SmallIntegerField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='observation',
            name='humidity_max_time',
            field=models.DateTimeField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='observation',
            name='humidity_min',
            field=models.SmallIntegerField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='observation',
            name='humidity_min_time',
            field=models.SmallIntegerField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='observation',
            name='inHumidity',
            field=models.SmallIntegerField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='observation',
            name='in_temp',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='observation',
            name='insolation_duration',
            field=models.SmallIntegerField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='observation',
            name='out_temp',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='observation',
            name='out_temp_max',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='observation',
            name='out_temp_max_time',
            field=models.DateTimeField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='observation',
            name='out_temp_min',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='observation',
            name='out_temp_min_time',
            field=models.DateTimeField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='observation',
            name='pressure',
            field=models.DecimalField(decimal_places=1, max_digits=5, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='observation',
            name='rain_rate_max',
            field=models.DecimalField(decimal_places=1, max_digits=5, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='observation',
            name='rain_rate_max_time',
            field=models.DateTimeField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='observation',
            name='rain_sum',
            field=models.DecimalField(decimal_places=1, max_digits=5, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='observation',
            name='soil_temp',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='observation',
            name='soil_temp_min',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='observation',
            name='soil_temp_min_time',
            field=models.DateTimeField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='observation',
            name='solar_radiation',
            field=models.SmallIntegerField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='observation',
            name='uv',
            field=models.DecimalField(decimal_places=3, max_digits=5, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='observation',
            name='uv_indixe',
            field=models.SmallIntegerField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='observation',
            name='wind_dir',
            field=models.SmallIntegerField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='observation',
            name='wind_gust',
            field=models.DecimalField(decimal_places=1, max_digits=5, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='observation',
            name='wind_gust_dir',
            field=models.SmallIntegerField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='observation',
            name='wind_gust_time',
            field=models.DateTimeField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='observation',
            name='wind_speed',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='observation',
            name='windchill',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True, verbose_name=''),
        ),
    ]
