# Generated by Django 3.2.3 on 2021-07-02 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210504_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='aggall',
            name='duration_max',
            field=models.IntegerField(default=0, verbose_name='Max des durations des donnees de cette agregation'),
        ),
        migrations.AddField(
            model_name='aggday',
            name='duration_max',
            field=models.IntegerField(default=0, verbose_name='Max des durations des donnees de cette agregation'),
        ),
        migrations.AddField(
            model_name='agghour',
            name='duration_max',
            field=models.IntegerField(default=0, verbose_name='Max des durations des donnees de cette agregation'),
        ),
        migrations.AddField(
            model_name='aggmonth',
            name='duration_max',
            field=models.IntegerField(default=0, verbose_name='Max des durations des donnees de cette agregation'),
        ),
        migrations.AddField(
            model_name='aggyear',
            name='duration_max',
            field=models.IntegerField(default=0, verbose_name='Max des durations des donnees de cette agregation'),
        ),
        migrations.AddField(
            model_name='tmpaggall',
            name='duration_max',
            field=models.IntegerField(default=0, verbose_name='Max des durations des donnees de cette agregation'),
        ),
        migrations.AddField(
            model_name='tmpaggday',
            name='duration_max',
            field=models.IntegerField(default=0, verbose_name='Max des durations des donnees de cette agregation'),
        ),
        migrations.AddField(
            model_name='tmpagghour',
            name='duration_max',
            field=models.IntegerField(default=0, verbose_name='Max des durations des donnees de cette agregation'),
        ),
        migrations.AddField(
            model_name='tmpaggmonth',
            name='duration_max',
            field=models.IntegerField(default=0, verbose_name='Max des durations des donnees de cette agregation'),
        ),
        migrations.AddField(
            model_name='tmpaggyear',
            name='duration_max',
            field=models.IntegerField(default=0, verbose_name='Max des durations des donnees de cette agregation'),
        ),
    ]
