# Generated by Django 4.1.7 on 2024-02-16 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_init_timescaledb'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesure',
            name='convert',
            field=models.JSONField(default=dict, null=True, verbose_name='Conversion'),
        ),
    ]
