# Generated by Django 3.1.7 on 2021-03-23 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210320_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agg_day',
            name='start_dat',
            field=models.CharField(max_length=20, verbose_name='start date'),
        ),
        migrations.AlterField(
            model_name='agg_global',
            name='start_dat',
            field=models.CharField(max_length=20, verbose_name='start date'),
        ),
        migrations.AlterField(
            model_name='agg_hour',
            name='start_dat',
            field=models.CharField(max_length=20, verbose_name='start date'),
        ),
        migrations.AlterField(
            model_name='agg_month',
            name='start_dat',
            field=models.CharField(max_length=20, verbose_name='start date'),
        ),
        migrations.AlterField(
            model_name='agg_year',
            name='start_dat',
            field=models.CharField(max_length=20, verbose_name='start date'),
        ),
        migrations.AlterField(
            model_name='exclusion',
            name='start_dat',
            field=models.CharField(default='1900-01-01T00:00:00', max_length=20, verbose_name='start date'),
        ),
        migrations.AlterField(
            model_name='exclusion',
            name='stop_dat',
            field=models.CharField(default='2100-12-31T23:59:59', max_length=20, verbose_name='stop date'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='start_dat',
            field=models.CharField(default='1900-01-01T00:00:00', max_length=20, verbose_name='start date'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='stop_dat',
            field=models.CharField(max_length=20, verbose_name='stop date'),
        ),
        migrations.AlterField(
            model_name='poste',
            name='start_dat',
            field=models.CharField(default='1900-01-01T00:00:00', max_length=20, verbose_name='start date'),
        ),
        migrations.AlterField(
            model_name='poste',
            name='stop_dat',
            field=models.CharField(default='2100-12-31T23:59:59', max_length=20, verbose_name='stop date'),
        ),
    ]
