# Generated by Django 4.2.6 on 2023-12-28 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_init_timescaledb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mesure',
            name='csv_field',
        ),
        migrations.RemoveField(
            model_name='mesure',
            name='csv_minmax',
        ),
    ]
