# Generated by Django 5.0.2 on 2024-05-16 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_init_timescaledb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesure',
            name='j',
            field=models.JSONField(default=dict, null=True, verbose_name='json data'),
        ),
    ]
