# Generated by Django 4.0.4 on 2022-05-03 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_is_obs_extreme_id_obs_extreme_extremes_id_obs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exclusion',
            name='mesure',
        ),
    ]
