# Generated by Django 4.2.6 on 2023-12-17 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_mesure_csv_field_mesure_csv_mimax'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mesure',
            old_name='csv_mimax',
            new_name='csv_minmax',
        ),
    ]
