# Generated by Django 3.1.7 on 2021-03-24 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210323_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observation',
            name='start_dat',
        ),
        migrations.AddField(
            model_name='observation',
            name='agg_start_dat',
            field=models.CharField(default='1900-01-01T00:00:00', max_length=20, verbose_name='date agregation horaire utilisée'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='stop_dat',
            field=models.CharField(max_length=20, verbose_name='stop date, date de la mesure'),
        ),
    ]
