# Generated by Django 4.2.6 on 2023-12-18 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_poste_meteor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='xmax',
            old_name='obs',
            new_name='obs_id',
        ),
        migrations.RenameField(
            model_name='xmin',
            old_name='obs',
            new_name='obs_id',
        ),
    ]
