# Generated by Django 3.1.7 on 2021-03-07 09:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210307_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agg_day',
            name='start_dat',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='agg_global',
            name='start_dat',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='agg_hour',
            name='start_dat',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='agg_month',
            name='start_dat',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='agg_year',
            name='start_dat',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
