# Generated by Django 4.2.6 on 2024-01-18 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_mesure_max_deca_remove_mesure_min_deca_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='poste',
            name='last_date_per_mesure',
            field=models.JSONField(default=dict, null=True, verbose_name='derniere date par mesure'),
        ),
    ]
