# Generated by Django 4.2.6 on 2024-01-03 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_mesure_csv_field_remove_mesure_csv_minmax'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xmax',
            name='max_time',
        ),
        migrations.RemoveField(
            model_name='xmin',
            name='min_time',
        ),
    ]
