# Generated by Django 4.0.4 on 2022-06-14 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_mesure_field_dir'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Parameter',
        ),
    ]
