# Generated by Django 4.0.4 on 2022-05-29 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_poste_last_data_poste_last_data_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poste',
            old_name='last_data',
            new_name='last_data_date',
        ),
    ]
