# Generated by Django 3.1.5 on 2021-02-09 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210209_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agg_day',
            name='j',
        ),
        migrations.RemoveField(
            model_name='agg_global',
            name='j',
        ),
        migrations.RemoveField(
            model_name='agg_month',
            name='j',
        ),
        migrations.RemoveField(
            model_name='agg_year',
            name='j',
        ),
        migrations.AddField(
            model_name='agg_day',
            name='barometer_avg',
            field=models.DecimalField(decimal_places=1, max_digits=5, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_day',
            name='barometer_duration',
            field=models.IntegerField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_day',
            name='barometer_max',
            field=models.DecimalField(decimal_places=1, max_digits=5, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_day',
            name='barometer_max_time',
            field=models.DateTimeField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_day',
            name='barometer_min',
            field=models.DecimalField(decimal_places=1, max_digits=5, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_day',
            name='barometer_min_time',
            field=models.DateTimeField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_day',
            name='barometer_sum',
            field=models.IntegerField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_day',
            name='dewpoint_max',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_day',
            name='dewpoint_max_time',
            field=models.DateTimeField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_day',
            name='dewpoint_min',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_day',
            name='dewpoint_min_time',
            field=models.DateTimeField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_day',
            name='etp_max',
            field=models.DecimalField(decimal_places=3, max_digits=5, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_day',
            name='etp_max_time',
            field=models.DateTimeField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_day',
            name='etp_min',
            field=models.DecimalField(decimal_places=3, max_digits=5, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_day',
            name='etp_min_time',
            field=models.DateTimeField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_day',
            name='heat_index_max',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_day',
            name='heat_index_max_time',
            field=models.DateTimeField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_day',
            name='humidity_max',
            field=models.SmallIntegerField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_day',
            name='humidity_max_time',
            field=models.DateTimeField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_day',
            name='humidity_min',
            field=models.SmallIntegerField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_day',
            name='humidity_min_time',
            field=models.SmallIntegerField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_day',
            name='in_humidity_max',
            field=models.SmallIntegerField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_day',
            name='in_humidity_max_time',
            field=models.DateTimeField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_day',
            name='in_humidity_min',
            field=models.SmallIntegerField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_day',
            name='in_humidity_min_time',
            field=models.SmallIntegerField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_day',
            name='in_temp_max',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_day',
            name='in_temp_max_time',
            field=models.DateTimeField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_day',
            name='in_temp_min',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_day',
            name='in_temp_min_time',
            field=models.DateTimeField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_day',
            name='out_temp_avg',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_day',
            name='out_temp_duration',
            field=models.IntegerField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_day',
            name='out_temp_max',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_day',
            name='out_temp_max_time',
            field=models.DateTimeField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_day',
            name='out_temp_min',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_day',
            name='out_temp_min_time',
            field=models.DateTimeField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_day',
            name='out_temp_sum',
            field=models.IntegerField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_day',
            name='rain_avg',
            field=models.DecimalField(decimal_places=1, max_digits=5, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_day',
            name='rain_duration',
            field=models.IntegerField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_day',
            name='rain_rate_max',
            field=models.DecimalField(decimal_places=1, max_digits=5, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_day',
            name='rain_rate_max_time',
            field=models.DateTimeField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_day',
            name='rain_sum',
            field=models.IntegerField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_day',
            name='rx_avg',
            field=models.SmallIntegerField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_day',
            name='rx_duration',
            field=models.IntegerField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_day',
            name='rx_max',
            field=models.SmallIntegerField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_day',
            name='rx_max_time',
            field=models.DateTimeField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_day',
            name='rx_min',
            field=models.SmallIntegerField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_day',
            name='rx_min_time',
            field=models.DateTimeField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_day',
            name='rx_sum',
            field=models.IntegerField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_day',
            name='soil_temp_in_time',
            field=models.DateTimeField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_day',
            name='soil_temp_min',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_day',
            name='uv_max',
            field=models.DecimalField(decimal_places=3, max_digits=5, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_day',
            name='uv_max_time',
            field=models.DateTimeField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_day',
            name='uv_min',
            field=models.DecimalField(decimal_places=3, max_digits=5, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_day',
            name='uv_min_time',
            field=models.DateTimeField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_day',
            name='voltage_avg',
            field=models.SmallIntegerField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_day',
            name='voltage_duration',
            field=models.IntegerField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_day',
            name='voltage_max',
            field=models.SmallIntegerField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_day',
            name='voltage_max_time',
            field=models.DateTimeField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_day',
            name='voltage_min',
            field=models.SmallIntegerField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_day',
            name='voltage_min_time',
            field=models.DateTimeField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_day',
            name='voltage_sum',
            field=models.IntegerField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_day',
            name='win_speed_duration',
            field=models.IntegerField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_day',
            name='wind_dir_avg',
            field=models.SmallIntegerField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_day',
            name='wind_dir_duration',
            field=models.IntegerField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_day',
            name='wind_dir_sum',
            field=models.IntegerField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_day',
            name='wind_gust',
            field=models.DecimalField(decimal_places=1, max_digits=5, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_day',
            name='wind_gust_dir',
            field=models.SmallIntegerField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_day',
            name='wind_gust_time',
            field=models.DateTimeField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_day',
            name='wind_speed_avg',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_day',
            name='wind_speed_sum',
            field=models.IntegerField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_day',
            name='windchill_max',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_day',
            name='windchill_max_time',
            field=models.DateTimeField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_day',
            name='windchill_min',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_day',
            name='windchill_min_time',
            field=models.DateTimeField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_global',
            name='barometer_avg',
            field=models.DecimalField(decimal_places=1, max_digits=5, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_global',
            name='barometer_duration',
            field=models.IntegerField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_global',
            name='barometer_max',
            field=models.DecimalField(decimal_places=1, max_digits=5, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_global',
            name='barometer_max_time',
            field=models.DateTimeField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_global',
            name='barometer_min',
            field=models.DecimalField(decimal_places=1, max_digits=5, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_global',
            name='barometer_min_time',
            field=models.DateTimeField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_global',
            name='barometer_sum',
            field=models.IntegerField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_global',
            name='dewpoint_max',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_global',
            name='dewpoint_max_time',
            field=models.DateTimeField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_global',
            name='dewpoint_min',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_global',
            name='dewpoint_min_time',
            field=models.DateTimeField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_global',
            name='etp_max',
            field=models.DecimalField(decimal_places=3, max_digits=5, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_global',
            name='etp_max_time',
            field=models.DateTimeField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_global',
            name='etp_min',
            field=models.DecimalField(decimal_places=3, max_digits=5, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_global',
            name='etp_min_time',
            field=models.DateTimeField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_global',
            name='heat_index_max',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_global',
            name='heat_index_max_time',
            field=models.DateTimeField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_global',
            name='humidity_max',
            field=models.SmallIntegerField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_global',
            name='humidity_max_time',
            field=models.DateTimeField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_global',
            name='humidity_min',
            field=models.SmallIntegerField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_global',
            name='humidity_min_time',
            field=models.SmallIntegerField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_global',
            name='in_humidity_max',
            field=models.SmallIntegerField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_global',
            name='in_humidity_max_time',
            field=models.DateTimeField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_global',
            name='in_humidity_min',
            field=models.SmallIntegerField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_global',
            name='in_humidity_min_time',
            field=models.SmallIntegerField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_global',
            name='in_temp_max',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_global',
            name='in_temp_max_time',
            field=models.DateTimeField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_global',
            name='in_temp_min',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_global',
            name='in_temp_min_time',
            field=models.DateTimeField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_global',
            name='out_temp_avg',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_global',
            name='out_temp_duration',
            field=models.IntegerField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_global',
            name='out_temp_max',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_global',
            name='out_temp_max_time',
            field=models.DateTimeField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_global',
            name='out_temp_min',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_global',
            name='out_temp_min_time',
            field=models.DateTimeField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_global',
            name='out_temp_sum',
            field=models.IntegerField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_global',
            name='rain_avg',
            field=models.DecimalField(decimal_places=1, max_digits=5, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_global',
            name='rain_duration',
            field=models.IntegerField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_global',
            name='rain_rate_max',
            field=models.DecimalField(decimal_places=1, max_digits=5, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_global',
            name='rain_rate_max_time',
            field=models.DateTimeField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_global',
            name='rain_sum',
            field=models.IntegerField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_global',
            name='rx_avg',
            field=models.SmallIntegerField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_global',
            name='rx_duration',
            field=models.IntegerField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_global',
            name='rx_max',
            field=models.SmallIntegerField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_global',
            name='rx_max_time',
            field=models.DateTimeField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_global',
            name='rx_min',
            field=models.SmallIntegerField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_global',
            name='rx_min_time',
            field=models.DateTimeField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_global',
            name='rx_sum',
            field=models.IntegerField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_global',
            name='soil_temp_in_time',
            field=models.DateTimeField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_global',
            name='soil_temp_min',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_global',
            name='uv_max',
            field=models.DecimalField(decimal_places=3, max_digits=5, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_global',
            name='uv_max_time',
            field=models.DateTimeField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_global',
            name='uv_min',
            field=models.DecimalField(decimal_places=3, max_digits=5, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_global',
            name='uv_min_time',
            field=models.DateTimeField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_global',
            name='voltage_avg',
            field=models.SmallIntegerField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_global',
            name='voltage_duration',
            field=models.IntegerField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_global',
            name='voltage_max',
            field=models.SmallIntegerField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_global',
            name='voltage_max_time',
            field=models.DateTimeField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_global',
            name='voltage_min',
            field=models.SmallIntegerField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_global',
            name='voltage_min_time',
            field=models.DateTimeField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_global',
            name='voltage_sum',
            field=models.IntegerField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_global',
            name='win_speed_duration',
            field=models.IntegerField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_global',
            name='wind_dir_avg',
            field=models.SmallIntegerField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_global',
            name='wind_dir_duration',
            field=models.IntegerField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_global',
            name='wind_dir_sum',
            field=models.IntegerField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_global',
            name='wind_gust',
            field=models.DecimalField(decimal_places=1, max_digits=5, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_global',
            name='wind_gust_dir',
            field=models.SmallIntegerField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_global',
            name='wind_gust_time',
            field=models.DateTimeField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_global',
            name='wind_speed_avg',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_global',
            name='wind_speed_sum',
            field=models.IntegerField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_global',
            name='windchill_max',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_global',
            name='windchill_max_time',
            field=models.DateTimeField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_global',
            name='windchill_min',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_global',
            name='windchill_min_time',
            field=models.DateTimeField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_month',
            name='barometer_avg',
            field=models.DecimalField(decimal_places=1, max_digits=5, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_month',
            name='barometer_duration',
            field=models.IntegerField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_month',
            name='barometer_max',
            field=models.DecimalField(decimal_places=1, max_digits=5, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_month',
            name='barometer_max_time',
            field=models.DateTimeField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_month',
            name='barometer_min',
            field=models.DecimalField(decimal_places=1, max_digits=5, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_month',
            name='barometer_min_time',
            field=models.DateTimeField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_month',
            name='barometer_sum',
            field=models.IntegerField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_month',
            name='dewpoint_max',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_month',
            name='dewpoint_max_time',
            field=models.DateTimeField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_month',
            name='dewpoint_min',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_month',
            name='dewpoint_min_time',
            field=models.DateTimeField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_month',
            name='etp_max',
            field=models.DecimalField(decimal_places=3, max_digits=5, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_month',
            name='etp_max_time',
            field=models.DateTimeField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_month',
            name='etp_min',
            field=models.DecimalField(decimal_places=3, max_digits=5, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_month',
            name='etp_min_time',
            field=models.DateTimeField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_month',
            name='heat_index_max',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_month',
            name='heat_index_max_time',
            field=models.DateTimeField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_month',
            name='humidity_max',
            field=models.SmallIntegerField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_month',
            name='humidity_max_time',
            field=models.DateTimeField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_month',
            name='humidity_min',
            field=models.SmallIntegerField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_month',
            name='humidity_min_time',
            field=models.SmallIntegerField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_month',
            name='in_humidity_max',
            field=models.SmallIntegerField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_month',
            name='in_humidity_max_time',
            field=models.DateTimeField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_month',
            name='in_humidity_min',
            field=models.SmallIntegerField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_month',
            name='in_humidity_min_time',
            field=models.SmallIntegerField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_month',
            name='in_temp_max',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_month',
            name='in_temp_max_time',
            field=models.DateTimeField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_month',
            name='in_temp_min',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_month',
            name='in_temp_min_time',
            field=models.DateTimeField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_month',
            name='out_temp_avg',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_month',
            name='out_temp_duration',
            field=models.IntegerField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_month',
            name='out_temp_max',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_month',
            name='out_temp_max_time',
            field=models.DateTimeField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_month',
            name='out_temp_min',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_month',
            name='out_temp_min_time',
            field=models.DateTimeField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_month',
            name='out_temp_sum',
            field=models.IntegerField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_month',
            name='rain_avg',
            field=models.DecimalField(decimal_places=1, max_digits=5, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_month',
            name='rain_duration',
            field=models.IntegerField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_month',
            name='rain_rate_max',
            field=models.DecimalField(decimal_places=1, max_digits=5, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_month',
            name='rain_rate_max_time',
            field=models.DateTimeField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_month',
            name='rain_sum',
            field=models.IntegerField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_month',
            name='rx_avg',
            field=models.SmallIntegerField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_month',
            name='rx_duration',
            field=models.IntegerField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_month',
            name='rx_max',
            field=models.SmallIntegerField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_month',
            name='rx_max_time',
            field=models.DateTimeField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_month',
            name='rx_min',
            field=models.SmallIntegerField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_month',
            name='rx_min_time',
            field=models.DateTimeField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_month',
            name='rx_sum',
            field=models.IntegerField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_month',
            name='soil_temp_in_time',
            field=models.DateTimeField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_month',
            name='soil_temp_min',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_month',
            name='uv_max',
            field=models.DecimalField(decimal_places=3, max_digits=5, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_month',
            name='uv_max_time',
            field=models.DateTimeField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_month',
            name='uv_min',
            field=models.DecimalField(decimal_places=3, max_digits=5, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_month',
            name='uv_min_time',
            field=models.DateTimeField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_month',
            name='voltage_avg',
            field=models.SmallIntegerField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_month',
            name='voltage_duration',
            field=models.IntegerField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_month',
            name='voltage_max',
            field=models.SmallIntegerField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_month',
            name='voltage_max_time',
            field=models.DateTimeField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_month',
            name='voltage_min',
            field=models.SmallIntegerField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_month',
            name='voltage_min_time',
            field=models.DateTimeField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_month',
            name='voltage_sum',
            field=models.IntegerField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_month',
            name='win_speed_duration',
            field=models.IntegerField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_month',
            name='wind_dir_avg',
            field=models.SmallIntegerField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_month',
            name='wind_dir_duration',
            field=models.IntegerField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_month',
            name='wind_dir_sum',
            field=models.IntegerField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_month',
            name='wind_gust',
            field=models.DecimalField(decimal_places=1, max_digits=5, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_month',
            name='wind_gust_dir',
            field=models.SmallIntegerField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_month',
            name='wind_gust_time',
            field=models.DateTimeField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_month',
            name='wind_speed_avg',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_month',
            name='wind_speed_sum',
            field=models.IntegerField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_month',
            name='windchill_max',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_month',
            name='windchill_max_time',
            field=models.DateTimeField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_month',
            name='windchill_min',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_month',
            name='windchill_min_time',
            field=models.DateTimeField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_year',
            name='barometer_avg',
            field=models.DecimalField(decimal_places=1, max_digits=5, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_year',
            name='barometer_duration',
            field=models.IntegerField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_year',
            name='barometer_max',
            field=models.DecimalField(decimal_places=1, max_digits=5, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_year',
            name='barometer_max_time',
            field=models.DateTimeField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_year',
            name='barometer_min',
            field=models.DecimalField(decimal_places=1, max_digits=5, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_year',
            name='barometer_min_time',
            field=models.DateTimeField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_year',
            name='barometer_sum',
            field=models.IntegerField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_year',
            name='dewpoint_max',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_year',
            name='dewpoint_max_time',
            field=models.DateTimeField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_year',
            name='dewpoint_min',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_year',
            name='dewpoint_min_time',
            field=models.DateTimeField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_year',
            name='etp_max',
            field=models.DecimalField(decimal_places=3, max_digits=5, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_year',
            name='etp_max_time',
            field=models.DateTimeField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_year',
            name='etp_min',
            field=models.DecimalField(decimal_places=3, max_digits=5, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_year',
            name='etp_min_time',
            field=models.DateTimeField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_year',
            name='heat_index_max',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_year',
            name='heat_index_max_time',
            field=models.DateTimeField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_year',
            name='humidity_max',
            field=models.SmallIntegerField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_year',
            name='humidity_max_time',
            field=models.DateTimeField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_year',
            name='humidity_min',
            field=models.SmallIntegerField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_year',
            name='humidity_min_time',
            field=models.SmallIntegerField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_year',
            name='in_humidity_max',
            field=models.SmallIntegerField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_year',
            name='in_humidity_max_time',
            field=models.DateTimeField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_year',
            name='in_humidity_min',
            field=models.SmallIntegerField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_year',
            name='in_humidity_min_time',
            field=models.SmallIntegerField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_year',
            name='in_temp_max',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_year',
            name='in_temp_max_time',
            field=models.DateTimeField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_year',
            name='in_temp_min',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_year',
            name='in_temp_min_time',
            field=models.DateTimeField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_year',
            name='out_temp_avg',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_year',
            name='out_temp_duration',
            field=models.IntegerField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_year',
            name='out_temp_max',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_year',
            name='out_temp_max_time',
            field=models.DateTimeField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_year',
            name='out_temp_min',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_year',
            name='out_temp_min_time',
            field=models.DateTimeField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_year',
            name='out_temp_sum',
            field=models.IntegerField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_year',
            name='rain_avg',
            field=models.DecimalField(decimal_places=1, max_digits=5, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_year',
            name='rain_duration',
            field=models.IntegerField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_year',
            name='rain_rate_max',
            field=models.DecimalField(decimal_places=1, max_digits=5, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_year',
            name='rain_rate_max_time',
            field=models.DateTimeField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_year',
            name='rain_sum',
            field=models.IntegerField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_year',
            name='rx_avg',
            field=models.SmallIntegerField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_year',
            name='rx_duration',
            field=models.IntegerField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_year',
            name='rx_max',
            field=models.SmallIntegerField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_year',
            name='rx_max_time',
            field=models.DateTimeField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_year',
            name='rx_min',
            field=models.SmallIntegerField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_year',
            name='rx_min_time',
            field=models.DateTimeField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_year',
            name='rx_sum',
            field=models.IntegerField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_year',
            name='soil_temp_in_time',
            field=models.DateTimeField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_year',
            name='soil_temp_min',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_year',
            name='uv_max',
            field=models.DecimalField(decimal_places=3, max_digits=5, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_year',
            name='uv_max_time',
            field=models.DateTimeField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_year',
            name='uv_min',
            field=models.DecimalField(decimal_places=3, max_digits=5, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_year',
            name='uv_min_time',
            field=models.DateTimeField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_year',
            name='voltage_avg',
            field=models.SmallIntegerField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_year',
            name='voltage_duration',
            field=models.IntegerField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_year',
            name='voltage_max',
            field=models.SmallIntegerField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_year',
            name='voltage_max_time',
            field=models.DateTimeField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_year',
            name='voltage_min',
            field=models.SmallIntegerField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_year',
            name='voltage_min_time',
            field=models.DateTimeField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_year',
            name='voltage_sum',
            field=models.IntegerField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_year',
            name='win_speed_duration',
            field=models.IntegerField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_year',
            name='wind_dir_avg',
            field=models.SmallIntegerField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_year',
            name='wind_dir_duration',
            field=models.IntegerField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_year',
            name='wind_dir_sum',
            field=models.IntegerField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_year',
            name='wind_gust',
            field=models.DecimalField(decimal_places=1, max_digits=5, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_year',
            name='wind_gust_dir',
            field=models.SmallIntegerField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_year',
            name='wind_gust_time',
            field=models.DateTimeField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_year',
            name='wind_speed_avg',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_year',
            name='wind_speed_sum',
            field=models.IntegerField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_year',
            name='windchill_max',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_year',
            name='windchill_max_time',
            field=models.DateTimeField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_year',
            name='windchill_min',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='agg_year',
            name='windchill_min_time',
            field=models.DateTimeField(null=True, verbose_name=''),
        ),
    ]
