# Generated by Django 4.0.4 on 2022-05-03 21:20

import app.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_exclusion_mesure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exclusion',
            name='start_dat',
            field=app.models.DateTimeFieldNoTZ(default='1900-01-01T00:00:00', max_length=20, verbose_name='Date début exclusion'),
        ),
        migrations.AlterField(
            model_name='exclusion',
            name='stop_dat',
            field=app.models.DateTimeFieldNoTZ(default='2100-12-31T23:59:59', max_length=20, verbose_name='Date fin exclusion'),
        ),
        migrations.AlterField(
            model_name='extreme',
            name='max_time',
            field=app.models.DateTimeFieldNoTZ(null=True, verbose_name='date du maximum'),
        ),
        migrations.AlterField(
            model_name='extreme',
            name='min_time',
            field=app.models.DateTimeFieldNoTZ(null=True, verbose_name='date du minimum'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='dat',
            field=app.models.DateTimeFieldNoTZ(max_length=30, verbose_name="date'"),
        ),
        migrations.AlterField(
            model_name='observation',
            name='time',
            field=app.models.DateTimeFieldNoTZ(verbose_name='date fin période observation'),
        ),
        migrations.AlterField(
            model_name='poste',
            name='start_dat',
            field=app.models.DateTimeFieldNoTZ(default='1900-01-01T00:00:00', null=True, verbose_name="Date d'activation"),
        ),
        migrations.AlterField(
            model_name='poste',
            name='stop_dat',
            field=app.models.DateTimeFieldNoTZ(default='2100-12-31T23:59:59', null=True, verbose_name='Date de désactivation'),
        ),
    ]
