# Generated by Django 3.1.7 on 2021-04-07 15:56

import app.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210407_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agg_day',
            name='j',
            field=app.models.DateJSONField(),
        ),
        migrations.AlterField(
            model_name='agg_global',
            name='j',
            field=app.models.DateJSONField(),
        ),
        migrations.AlterField(
            model_name='agg_hour',
            name='j',
            field=app.models.DateJSONField(),
        ),
        migrations.AlterField(
            model_name='agg_month',
            name='j',
            field=app.models.DateJSONField(),
        ),
        migrations.AlterField(
            model_name='agg_year',
            name='j',
            field=app.models.DateJSONField(),
        ),
        migrations.AlterField(
            model_name='extreme_todo',
            name='j_invalid',
            field=app.models.DateJSONField(),
        ),
        migrations.AlterField(
            model_name='observation',
            name='j',
            field=app.models.DateJSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='observation',
            name='j_agg',
            field=app.models.DateJSONField(default=dict),
        ),
    ]
