# Generated by Django 3.2.9 on 2021-12-09 18:29

import app.models
import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20211209_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='duration',
            field=models.IntegerField(default=0, verbose_name='durée période'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='j',
            field=app.models.DateJSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='mesures Json'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='j_agg',
            field=app.models.DateJSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='donées pré-agrégées'),
        ),
    ]
