# Generated by Django 3.1.7 on 2021-03-24 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210324_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poste',
            name='agg_min_extreme',
        ),
        migrations.RemoveField(
            model_name='poste',
            name='cas_gestion_extreme',
        ),
    ]
