# Generated by Django 4.2.6 on 2023-12-19 20:22

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_obs_xmax_obs_id_rename_obs_xmin_obs_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='poste',
            name='stop_date',
            field=app.models.DateTimeFieldNoTZ(null=True, verbose_name='Datetime local de stop de la station'),
        ),
        migrations.AlterField(
            model_name='mesure',
            name='archive_col',
            field=models.CharField(max_length=20, null=True, verbose_name='nom colonne table weewx.archive'),
        ),
        migrations.AlterField(
            model_name='mesure',
            name='csv_minmax',
            field=models.JSONField(default=dict, null=True, verbose_name='Nom champs min, minTime, max, maxTime maxDir'),
        ),
        migrations.AlterField(
            model_name='mesure',
            name='json_input',
            field=models.CharField(max_length=20, null=True, verbose_name='Clé utilisée dans le json'),
        ),
    ]
