# Generated by Django 3.1.7 on 2021-03-31 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210324_1637'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extreme_todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=1, verbose_name='Aggregation level')),
                ('start_dat', models.CharField(max_length=20, verbose_name="start date de l agregation'")),
                ('invalid_type', models.CharField(max_length=3, verbose_name='Type Invalidation (max or min)')),
                ('j_invalid', models.JSONField(default=dict)),
                ('poste_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.poste')),
            ],
            options={
                'db_table': 'extreme_todo',
            },
        ),
        migrations.CreateModel(
            name='Agg_todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_dat', models.CharField(max_length=20, verbose_name='stop date, date de la mesure')),
                ('j_dv', models.JSONField(default=dict)),
                ('obs_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.observation')),
                ('poste_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.poste')),
            ],
            options={
                'db_table': 'agg_todo',
            },
        ),
    ]
