# Generated by Django 3.1.7 on 2021-04-07 17:03

import app.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210407_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='j',
            field=app.models.DateJSONField(),
        ),
        migrations.AlterField(
            model_name='observation',
            name='j_agg',
            field=app.models.DateJSONField(),
        ),
    ]
