# Generated by Django 4.0.4 on 2022-05-11 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_exclusion_start_dat_alter_exclusion_stop_dat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='duration',
            field=models.IntegerField(default=0, null=True, verbose_name='durée période'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='j',
            field=models.JSONField(default=dict, null=True, verbose_name='données autres'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='qa_check_done',
            field=models.BooleanField(default=False, null=True, verbose_name='qa_check_done'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='qa_incidents',
            field=models.IntegerField(default=0, null=True, verbose_name='qa_incidents'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='qa_modifications',
            field=models.IntegerField(default=0, null=True, verbose_name='qa_modifications'),
        ),
    ]
