# Generated by Django 3.1.7 on 2021-03-08 06:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210307_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='start_dat',
            field=models.DateTimeField(default=datetime.datetime(1900, 1, 1, 0, 0, tzinfo=utc)),
        ),
    ]
