# Generated by Django 3.1.7 on 2021-04-08 14:09

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210407_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agg_todo',
            name='j_dv',
            field=models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='default_values coming from obs processing'),
        ),
        migrations.AlterField(
            model_name='agg_todo',
            name='j_error',
            field=models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='error reporting'),
        ),
        migrations.AlterField(
            model_name='exclusion',
            name='value',
            field=models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='JsonB'),
        ),
        migrations.AlterField(
            model_name='typeinstrument',
            name='model_value',
            field=models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='JsonB'),
        ),
    ]
