# Generated by Django 3.2.9 on 2021-12-09 19:14

import app.models
import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20211209_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agghisto',
            name='agg_id',
            field=models.IntegerField(default=0, verbose_name='Aggregation_id updated'),
        ),
        migrations.AlterField(
            model_name='agghisto',
            name='agg_level',
            field=models.CharField(max_length=2, verbose_name='level'),
        ),
        migrations.AlterField(
            model_name='agghisto',
            name='delta_duration',
            field=models.IntegerField(verbose_name='Delta des durées'),
        ),
        migrations.AlterField(
            model_name='agghisto',
            name='j',
            field=app.models.DateJSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='Delta agrégation'),
        ),
        migrations.AlterField(
            model_name='agghisto',
            name='obs_id',
            field=models.IntegerField(default=0, verbose_name='Observation source'),
        ),
    ]
