# Generated by Django 3.1.5 on 2021-02-11 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210209_1353'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TypeData',
            new_name='TypeInstrument',
        ),
    ]
