# Generated by Django 3.1.7 on 2021-04-04 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_agg_todo_extreme_todo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agg_todo',
            name='poste_id',
        ),
        migrations.RemoveField(
            model_name='agg_todo',
            name='stop_dat',
        ),
        migrations.AddField(
            model_name='agg_todo',
            name='priority',
            field=models.BooleanField(default=False, null=True, verbose_name='priority flag for one data mesure only'),
        ),
        migrations.AlterField(
            model_name='agg_todo',
            name='j_dv',
            field=models.JSONField(default=dict, verbose_name='default_values coming from obs processing'),
        ),
    ]
