# Generated by Django 4.0.4 on 2022-05-13 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_observation_duration_alter_observation_j_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extreme',
            old_name='time',
            new_name='date',
        ),
    ]
