# Generated by Django 3.1.7 on 2021-04-08 14:31

import app.models
import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210408_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agg_day',
            name='j',
            field=models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AlterField(
            model_name='agg_global',
            name='j',
            field=models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AlterField(
            model_name='agg_hour',
            name='j',
            field=models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AlterField(
            model_name='agg_month',
            name='j',
            field=models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AlterField(
            model_name='agg_year',
            name='j',
            field=models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AlterField(
            model_name='extreme_todo',
            name='j_invalid',
            field=models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AlterField(
            model_name='observation',
            name='j',
            field=app.models.DateJSONField(encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AlterField(
            model_name='observation',
            name='j_agg',
            field=app.models.DateJSONField(encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
    ]
