# Generated by Django 3.2.9 on 2021-12-09 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20211209_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agghisto',
            name='agg_id',
            field=models.IntegerField(default=0, verbose_name='Agg_id'),
        ),
        migrations.AlterField(
            model_name='agghisto',
            name='delta_duration',
            field=models.IntegerField(verbose_name='Delta durées'),
        ),
        migrations.AlterField(
            model_name='agghisto',
            name='obs_id',
            field=models.IntegerField(default=0, verbose_name='Obs_id'),
        ),
    ]
