# Generated by Django 3.1.7 on 2021-04-04 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210404_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='extreme_todo',
            name='status',
            field=models.IntegerField(default=0, verbose_name='status, 0: wait, 9: error, 99: processed'),
        ),
    ]
