# Generated by Django 3.1.5 on 2021-02-11 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210211_0536'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='typeinstrument',
            table='type_instrument',
        ),
    ]
