# Generated by Django 3.1.7 on 2021-04-08 14:33

import app.models
import django.core.serializers.json
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210408_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agg_day',
            name='j',
            field=app.models.DateJSONField(encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AlterField(
            model_name='agg_global',
            name='j',
            field=app.models.DateJSONField(encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AlterField(
            model_name='agg_hour',
            name='j',
            field=app.models.DateJSONField(encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AlterField(
            model_name='agg_month',
            name='j',
            field=app.models.DateJSONField(encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AlterField(
            model_name='agg_todo',
            name='j_dv',
            field=app.models.DateJSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='default_values coming from obs processing'),
        ),
        migrations.AlterField(
            model_name='agg_todo',
            name='j_error',
            field=app.models.DateJSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='error reporting'),
        ),
        migrations.AlterField(
            model_name='agg_year',
            name='j',
            field=app.models.DateJSONField(encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AlterField(
            model_name='exclusion',
            name='value',
            field=app.models.DateJSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='JsonB'),
        ),
        migrations.AlterField(
            model_name='extreme_todo',
            name='j_invalid',
            field=app.models.DateJSONField(encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AlterField(
            model_name='typeinstrument',
            name='model_value',
            field=app.models.DateJSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='JsonB'),
        ),
    ]
