# Generated by Django 3.1.7 on 2021-04-04 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_extreme_todo_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='agg_todo',
            name='status',
            field=models.IntegerField(default=0, verbose_name='status, 0: wait, 9: error, 99: processed'),
        ),
    ]
