# Generated by Django 3.2.9 on 2021-12-10 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20211209_1917'),
    ]

    operations = [
        migrations.CreateModel(
            name='AggHistoByAgg',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('app.agghisto',),
        ),
        migrations.CreateModel(
            name='AggHistoByObs',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('app.agghisto',),
        ),
        migrations.AlterField(
            model_name='agghour',
            name='duration_max',
            field=models.IntegerField(default=0, verbose_name='Durée max'),
        ),
        migrations.AlterField(
            model_name='agghour',
            name='duration_sum',
            field=models.IntegerField(default=0, verbose_name='Durées agrégées'),
        ),
    ]
