# Generated by Django 4.0.4 on 2022-05-13 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_annotation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='duration',
            field=models.SmallIntegerField(default=0, null=True, verbose_name='durée période'),
        ),
    ]
