# Generated by Django 3.1.5 on 2021-02-11 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210211_0537'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exclusion',
            old_name='type_data',
            new_name='type_instrument',
        ),
    ]
