# Generated by Django 3.1.5 on 2021-02-11 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210211_0539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agg_day',
            name='duration',
            field=models.IntegerField(default=300),
        ),
        migrations.AlterField(
            model_name='agg_day',
            name='qa_incidents',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='agg_day',
            name='qa_modifications',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='agg_global',
            name='duration',
            field=models.IntegerField(default=300),
        ),
        migrations.AlterField(
            model_name='agg_global',
            name='qa_incidents',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='agg_global',
            name='qa_modifications',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='agg_hour',
            name='duration',
            field=models.IntegerField(default=500, verbose_name='duration'),
        ),
        migrations.AlterField(
            model_name='agg_hour',
            name='qa_incidents',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='agg_hour',
            name='qa_modifications',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='agg_month',
            name='duration',
            field=models.IntegerField(default=300),
        ),
        migrations.AlterField(
            model_name='agg_month',
            name='qa_incidents',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='agg_month',
            name='qa_modifications',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='agg_year',
            name='duration',
            field=models.IntegerField(default=300),
        ),
        migrations.AlterField(
            model_name='agg_year',
            name='qa_incidents',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='agg_year',
            name='qa_modifications',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='observation',
            name='qa_incidents',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='observation',
            name='qa_modifications',
            field=models.IntegerField(default=0),
        ),
    ]
