# Generated by Django 4.0.4 on 2022-05-13 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_observation_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poste',
            old_name='latitude',
            new_name='lat',
        ),
        migrations.RenameField(
            model_name='poste',
            old_name='longitude',
            new_name='long',
        ),
    ]
