# Generated by Django 3.2.9 on 2021-12-10 12:26

import app.models
import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20211210_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aggall',
            name='duration_max',
            field=models.IntegerField(default=0, verbose_name='Durée max'),
        ),
        migrations.AlterField(
            model_name='aggall',
            name='duration_sum',
            field=models.IntegerField(default=0, verbose_name='Durées agrégées'),
        ),
        migrations.AlterField(
            model_name='aggall',
            name='j',
            field=app.models.DateJSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='Agrégations'),
        ),
        migrations.AlterField(
            model_name='aggday',
            name='duration_max',
            field=models.IntegerField(default=0, verbose_name='Durée max'),
        ),
        migrations.AlterField(
            model_name='aggday',
            name='duration_sum',
            field=models.IntegerField(default=0, verbose_name='Durées agrégées'),
        ),
        migrations.AlterField(
            model_name='aggday',
            name='j',
            field=app.models.DateJSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='Agrégations'),
        ),
        migrations.AlterField(
            model_name='agghour',
            name='j',
            field=app.models.DateJSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='Agrégations'),
        ),
        migrations.AlterField(
            model_name='aggmonth',
            name='duration_max',
            field=models.IntegerField(default=0, verbose_name='Durée max'),
        ),
        migrations.AlterField(
            model_name='aggmonth',
            name='duration_sum',
            field=models.IntegerField(default=0, verbose_name='Durées agrégées'),
        ),
        migrations.AlterField(
            model_name='aggmonth',
            name='j',
            field=app.models.DateJSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='Agrégations'),
        ),
        migrations.AlterField(
            model_name='aggyear',
            name='duration_max',
            field=models.IntegerField(default=0, verbose_name='Durée max'),
        ),
        migrations.AlterField(
            model_name='aggyear',
            name='duration_sum',
            field=models.IntegerField(default=0, verbose_name='Durées agrégées'),
        ),
        migrations.AlterField(
            model_name='aggyear',
            name='j',
            field=app.models.DateJSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='Agrégations'),
        ),
        migrations.AlterField(
            model_name='tmpaggall',
            name='duration_max',
            field=models.IntegerField(default=0, verbose_name='Durée max'),
        ),
        migrations.AlterField(
            model_name='tmpaggall',
            name='duration_sum',
            field=models.IntegerField(default=0, verbose_name='Durées agrégées'),
        ),
        migrations.AlterField(
            model_name='tmpaggall',
            name='j',
            field=app.models.DateJSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='Agrégations'),
        ),
        migrations.AlterField(
            model_name='tmpaggday',
            name='duration_max',
            field=models.IntegerField(default=0, verbose_name='Durée max'),
        ),
        migrations.AlterField(
            model_name='tmpaggday',
            name='duration_sum',
            field=models.IntegerField(default=0, verbose_name='Durées agrégées'),
        ),
        migrations.AlterField(
            model_name='tmpaggday',
            name='j',
            field=app.models.DateJSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='Agrégations'),
        ),
        migrations.AlterField(
            model_name='tmpagghour',
            name='duration_max',
            field=models.IntegerField(default=0, verbose_name='Durée max'),
        ),
        migrations.AlterField(
            model_name='tmpagghour',
            name='duration_sum',
            field=models.IntegerField(default=0, verbose_name='Durées agrégées'),
        ),
        migrations.AlterField(
            model_name='tmpagghour',
            name='j',
            field=app.models.DateJSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='Agrégations'),
        ),
        migrations.AlterField(
            model_name='tmpaggmonth',
            name='duration_max',
            field=models.IntegerField(default=0, verbose_name='Durée max'),
        ),
        migrations.AlterField(
            model_name='tmpaggmonth',
            name='duration_sum',
            field=models.IntegerField(default=0, verbose_name='Durées agrégées'),
        ),
        migrations.AlterField(
            model_name='tmpaggmonth',
            name='j',
            field=app.models.DateJSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='Agrégations'),
        ),
        migrations.AlterField(
            model_name='tmpaggyear',
            name='duration_max',
            field=models.IntegerField(default=0, verbose_name='Durée max'),
        ),
        migrations.AlterField(
            model_name='tmpaggyear',
            name='duration_sum',
            field=models.IntegerField(default=0, verbose_name='Durées agrégées'),
        ),
        migrations.AlterField(
            model_name='tmpaggyear',
            name='j',
            field=app.models.DateJSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='Agrégations'),
        ),
    ]
