# Generated by Django 3.1.7 on 2021-04-04 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_agg_todo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agg_todo',
            name='priority',
            field=models.IntegerField(default=9, null=True, verbose_name='priority, 0: one current-data, 9: multiple current-data'),
        ),
    ]
