# Generated by Django 3.1.7 on 2021-04-07 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20210404_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='agg_todo',
            name='j_error',
            field=models.JSONField(default=dict, verbose_name='error reporting'),
        ),
    ]
