# Generated by Django 4.0.4 on 2022-05-21 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_latitude_poste_lat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='observation',
            old_name='etp_sum',
            new_name='et',
        ),
        migrations.RenameField(
            model_name='observation',
            old_name='uv_indice',
            new_name='uv',
        ),
        migrations.RemoveField(
            model_name='observation',
            name='soiltemp',
        ),
        migrations.AddField(
            model_name='observation',
            name='extra_humid1',
            field=models.FloatField(null=True, verbose_name='extra humidité 1'),
        ),
        migrations.AddField(
            model_name='observation',
            name='extra_humid2',
            field=models.FloatField(null=True, verbose_name='extra humidité 2'),
        ),
        migrations.AddField(
            model_name='observation',
            name='extra_temp1',
            field=models.FloatField(null=True, verbose_name='extra temperature 1'),
        ),
        migrations.AddField(
            model_name='observation',
            name='extra_temp2',
            field=models.FloatField(null=True, verbose_name='extra temperature 2'),
        ),
        migrations.AddField(
            model_name='observation',
            name='extra_temp3',
            field=models.FloatField(null=True, verbose_name='extra temperature 3'),
        ),
        migrations.AddField(
            model_name='observation',
            name='hail',
            field=models.FloatField(null=True, verbose_name='hail'),
        ),
        migrations.AddField(
            model_name='observation',
            name='hail_rate',
            field=models.FloatField(null=True, verbose_name='hail rate'),
        ),
        migrations.AddField(
            model_name='observation',
            name='heating_temp',
            field=models.FloatField(null=True, verbose_name='heating temp'),
        ),
        migrations.AddField(
            model_name='observation',
            name='leaf_temp1',
            field=models.FloatField(null=True, verbose_name='temp des feuilles no 1'),
        ),
        migrations.AddField(
            model_name='observation',
            name='leaf_temp2',
            field=models.FloatField(null=True, verbose_name='temp des feuilles no 2'),
        ),
        migrations.AddField(
            model_name='observation',
            name='leaf_wet1',
            field=models.FloatField(null=True, verbose_name='humidité des feuilles no 1'),
        ),
        migrations.AddField(
            model_name='observation',
            name='leaf_wet2',
            field=models.FloatField(null=True, verbose_name='humidité des feuilles no 2'),
        ),
        migrations.AddField(
            model_name='observation',
            name='soil_moist1',
            field=models.FloatField(null=True, verbose_name='humidité du sol niveau du sol'),
        ),
        migrations.AddField(
            model_name='observation',
            name='soil_moist2',
            field=models.FloatField(null=True, verbose_name='humidité du sol niveau 1'),
        ),
        migrations.AddField(
            model_name='observation',
            name='soil_moist3',
            field=models.FloatField(null=True, verbose_name='humidité du sol niveau 2'),
        ),
        migrations.AddField(
            model_name='observation',
            name='soil_moist4',
            field=models.FloatField(null=True, verbose_name='humidité du sol niveau 3'),
        ),
        migrations.AddField(
            model_name='observation',
            name='soil_temp1',
            field=models.FloatField(null=True, verbose_name='température du sol niveau du sol'),
        ),
        migrations.AddField(
            model_name='observation',
            name='soil_temp2',
            field=models.FloatField(null=True, verbose_name='température du sol niveau 1'),
        ),
        migrations.AddField(
            model_name='observation',
            name='soil_temp3',
            field=models.FloatField(null=True, verbose_name='température du sol niveau 2'),
        ),
        migrations.AddField(
            model_name='observation',
            name='soil_temp4',
            field=models.FloatField(null=True, verbose_name='température du sol niveau 3'),
        ),
    ]
