# Generated by Django 3.1.5 on 2021-02-11 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20210211_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agg_day',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='agg_global',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='agg_hour',
            name='duration',
            field=models.IntegerField(default=0, verbose_name='duration'),
        ),
        migrations.AlterField(
            model_name='agg_month',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='agg_year',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='observation',
            name='duration',
            field=models.IntegerField(default=0, verbose_name='duration'),
        ),
    ]
