# Generated by Django 4.0.4 on 2022-05-23 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_rename_etp_sum_observation_et_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='observation',
            old_name='humidity',
            new_name='out_humidity',
        ),
        migrations.RenameField(
            model_name='observation',
            old_name='humidity_omm',
            new_name='out_humidity_omm',
        ),
    ]
