# Generated by Django 3.1.5 on 2021-02-12 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20210211_1231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='observation',
            old_name='out_temp_min',
            new_name='out_temp_hour_min',
        ),
        migrations.RenameField(
            model_name='observation',
            old_name='out_temp_min_time',
            new_name='out_temp_hour_min_time',
        ),
        migrations.AddField(
            model_name='poste',
            name='fuseau_horaire',
            field=models.CharField(default='??', max_length=10, verbose_name='timezone de la station'),
        ),
    ]
