# Generated by Django 3.2.9 on 2021-12-26 11:35

import app.models
import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20211210_1308'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('dat', app.models.DateCharField(max_length=20, verbose_name="start date de l incident'")),
                ('source', models.CharField(max_length=20, verbose_name='source')),
                ('level', models.CharField(max_length=20, verbose_name='level')),
                ('reason', models.TextField(verbose_name='reason')),
                ('j', app.models.DateJSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='Details')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'db_table': 'incident',
            },
        ),
    ]
