# Generated by Django 3.2.9 on 2021-12-28 14:10

import app.models
import django.core.serializers.json
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_incident'),
    ]

    operations = [
        migrations.AddField(
            model_name='aggtodo',
            name='j_agg',
            field=app.models.DateJSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='default_values coming from obs processing'),
        ),
        migrations.AddField(
            model_name='tmpaggtodo',
            name='j_agg',
            field=app.models.DateJSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='default_values coming from obs processing'),
        ),
    ]
