# Generated by Django 4.0.4 on 2022-05-23 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_rename_humidity_observation_out_humidity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='wind_dir',
            field=models.FloatField(null=True, verbose_name='direction moyenne du vent sur la période'),
        ),
    ]
