# Generated by Django 4.0.4 on 2022-05-25 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_observation_wind_dir'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesure',
            name='json_input_bis',
            field=models.CharField(max_length=20, null=True, verbose_name='Autre clé utilisée dans le json'),
        ),
    ]
