# Generated by Django 3.2.9 on 2021-12-29 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20211228_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
