# Generated by Django 4.0.4 on 2022-05-25 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_mesure_json_input_bis'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesure',
            name='is_hourly',
            field=models.BooleanField(default=False, null=True, verbose_name='Must be agregated by hour(s) or more, not less'),
        ),
    ]
