# Generated by Django 3.2.9 on 2021-12-29 11:38

import app.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_incident_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='dat',
            field=app.models.DateCharField(max_length=30, verbose_name="start date de l incident'"),
        ),
    ]
