# Generated by Django 4.0.4 on 2022-05-25 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_mesure_is_hourly'),
    ]

    operations = [
        migrations.RenameField(
            model_name='observation',
            old_name='et',
            new_name='etp',
        ),
    ]
