# Generated by Django 4.0.4 on 2022-05-27 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_rename_et_observation_etp'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesure',
            name='archive_table',
            field=models.CharField(default=None, max_length=20, verbose_name='nom table weewx.archive'),
        ),
    ]
