# Generated by Django 4.0.4 on 2022-05-27 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_mesure_archive_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesure',
            name='archive_table',
            field=models.CharField(default=None, max_length=20, null=True, verbose_name='nom table weewx.archive'),
        ),
    ]
