---
server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /mnt/tmp/positions.yaml

clients:
  - url: http://172.17.0.3:3100/loki/api/v1/push

scrape_configs:
  - job_name: system
    pipeline_stages:
    static_configs:
    - targets:
      - localhost
      labels:
        job: varlogs
        __path__: /mnt/log/*.log

  - job_name: django
    pipeline_stages:
    static_configs:
    - targets:
      - localhost
      labels:
        job: django
        __path__: /mnt/django/django.log

