# Generated by Django 3.2.9 on 2022-05-01 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL("CREATE EXTENSION timescaledb;"),
        migrations.RunSQL(
            "ALTER TABLE obs DROP CONSTRAINT obs_pkey;"
        ),
        migrations.RunSQL("SELECT create_hypertable('obs', 'time');"),
        migrations.RunSQL(
            "SELECT set_chunk_time_interval('obs', 6048000000000);"
        ),
        migrations.RunSQL(
            "ALTER TABLE extremes DROP CONSTRAINT extremes_pkey;"
        ),
        migrations.RunSQL("SELECT create_hypertable('extremes', 'time');"),
        migrations.RunSQL(
            "SELECT set_chunk_time_interval('extremes', 25920000000000);"
        ),
        migrations.RunSQL(
            """
            create materialized view obs_day WITH (timescaledb.continuous) as
                select 
                    timescaledb_experimental.time_bucket_ng('1 day', time) as time,
                    poste_id,
                    avg(barometer) as barometer,
                    avg(barometer_omm) as barometer_omm,
                    avg(dewpoint) as dewpoint,
                    sum(etp) as etp,
                    avg(extra_humid1) as extra_humid1,
                    avg(extra_humid2) as extra_humid2,
                    avg(extra_temp1) as extra_temp1,
                    avg(extra_temp2) as extra_temp2,
                    avg(extra_temp3) as extra_temp3,
                    avg(hail) as hail,
                    avg(hail_rate) as hail_rate,
                    avg(heatindex) as heatindex,
                    avg(heating_temp) as heating_temp,
                    avg(in_humidity) as in_humidity,
                    avg(in_temp) as in_temp,
                    avg(leaf_temp1) as leaf_temp1,
                    avg(leaf_temp2) as leaf_temp2,
                    avg(leaf_wet1) as leaf_wet1,
                    avg(leaf_wet2) as leaf_wet2,
                    avg(out_humidity) as out_humidity,
                    avg(out_humidity_omm) as out_humidity_omm,
                    avg(out_temp) as out_temp,
                    avg(out_temp_omm) as out_temp_omm,
                    avg(pressure) as pressure,
                    max(radiation) as max_radiation,
                    sum(rain) as rain,
                    sum(rain_omm) as rain_omm,
                    avg(rain_rate) as rain_rate,
                    avg(rx) as rx,
                    avg(soil_moist1) as soil_moist1,
                    avg(soil_moist2) as soil_moist2,
                    avg(soil_moist3) as soil_moist3,
                    avg(soil_moist4) as soil_moist4,
                    avg(soil_temp1) as soil_temp1,
                    avg(soil_temp2) as soil_temp2,
                    avg(soil_temp3) as soil_temp3,
                    avg(soil_temp4) as soil_temp4,
                    max(uv) as max_uv,
                    avg(voltage) as voltage,
                    avg(wind) as wind,
                    max(wind_gust) as wind_gust,
                    avg(wind10) as wind10,
                    avg(wind10_omm) as wind10_omm,
                    avg(windchill) as windchill
                from obs
                group by 1,2
            """
        )
    ]
