# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:

scrape_configs:

  - job_name: 'prometheus'
    static_configs:
    - targets: ['10.5.0.10:9090']

  - job_name: 'grafana'
    static_configs:
    - targets: ['10.5.0.30:3000']

  - job_name: 'loki'
    static_configs:
    - targets: ['10.5.0.20:3100']

  - job_name: 'promtail'
    static_configs:
    - targets: ['10.5.0.40:9080']

  - job_name: 'node'
    static_configs:
    - targets: ['n10.5.0.100:9100']

  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
    - targets: ['10.5.0.50:8080']
