rsync -v tags.py root@jenny.meteor-oi.re:/home/weewx/weewx-4.8.0-1
rsync -v wee_json root@jenny.meteor-oi.re:/home/weewx/weewx-4.8.0-1
rsync -v units.py root@jenny.meteor-oi.re:/home/weewx/weewx-4.8.0-1
rsync -v engine.py root@jenny.meteor-oi.re:/home/weewx/weewx-4.8.0-1
rsync -v reportengine.py root@jenny.meteor-oi.re:/home/weewx/weewx-4.8.0-1
rsync -v cheetahgenerator.py root@jenny.meteor-oi.re:/home/weewx/weewx-4.8.0-1
rsync -v extensions.py root@jenny.meteor-oi.re:/home/weewx/weewx-4.8.0-1
rsync -v weewx_json.conf root@jenny.meteor-oi.re:/home/weewx/weewx-4.8.0-1
rsync -v skin_Bootstrap.conf root@jenny.meteor-oi.re:/home/weewx/weewx-4.8.0-1
rsync -v skin_Json.conf root@jenny.meteor-oi.re:/home/weewx/weewx-4.8.0-1
rsync -v skin_Images.conf root@jenny.meteor-oi.re:/home/weewx/weewx-4.8.0-1
rsync -v ../weewx-3.9.1-1/obs.meteor.YYYY-MM-DDTHH-mm.json.tmpl root@jenny.meteor-oi.re:/home/weewx/weewx-4.8.0-1
rsync -v ../weewx-3.9.1-1/arch.meteor.YYYY-MM-DDTHH-mm.json.tmpl root@jenny.meteor-oi.re:/home/weewx/weewx-4.8.0-1
rsync -v historygenerator.py root@jenny.meteor-oi.re:/home/weewx/weewx-4.8.0-1
rsync -v index.html.tmpl root@jenny.meteor-oi.re:/home/weewx/weewx-4.8.0-1
rsync -v cron.weewx root@jenny.meteor-oi.re:/home/weewx/weewx-4.8.0-1
rsync -v trans_json.sh root@jenny.meteor-oi.re:/home/weewx/weewx-4.8.0-1
rsync -v trans_json_local.sh root@jenny.meteor-oi.re:/home/weewx/weewx-4.8.0-1
rsync -v refresh_weewx.sh root@jenny.meteor-oi.re:/home/weewx/weewx-4.8.0-1
